### ISSUE TITLE
Pop-Up mit Hinweis, dass Browser nicht unterstützt wird für Internet Explorer

### ISSUE THREAD

**Issue by ChristinaGu** [wirDesign-communication-AG/wirHub-doc#10]
**Checkliste**
- [x] Hinweisbox umsetzen, siehe Design > als color zunächst $wd--font-color-regular, 
- [x] Variablen für background-color, icon-color und color hinterlegen
- [x] Toggle unter Einstellungen > Administration > Globale Einstellungen "Browser Hinweis anzeigen" bzw. "Show browser hint"
- [x] Funktion um Default-Text optional zu überschreiben 

**Texte**
Deutsch:
Der Microsoft Internet Explorer IE11 und ältere Browser werden nicht mehr unterstützt. Um den vollen Funktionsumfang einwandfrei und ohne Darstellungsprobleme genießen zu können, raten wir Ihnen, die neueste Version von Chrome, Firefox, Microsoft Edge oder einen anderen modernen Browser zu verwenden.

Englisch:
Microsoft Internet Explorer IE11 and older browsers are no longer supported. To be able to enjoy the full range of functions flawlessly and without display problems, we advise you to use the latest version of Chrome, Firefox, Microsoft Edge or another modern browser.

**Design**
https://share.goabstract.com/ae66f100-118a-4199-9c87-5f10a1e02ee7?collectionLayerId=0dce7258-39ae-4cc1-a258-9e01f6e2c666&mode=design

![84166B9F-D4A8-4317-816A-28F9E3F568C5](https://user-images.githubusercontent.com/8007132/115236565-c8346d00-a11b-11eb-8ec8-61516ad24572.png)

**Comment by pmdevelopment** [comment]
Abweichend zur Beschreibung wurde die Einstellung unter "Frontend => Anmelden" hinterlegt. Es wurde angemerkt, dass der Standard-Text möglicherweiße viel zu lang ist.

Style configs:

    $wd--login-browser-hint-color: $wd--font-color-regular !default;
    $wd--login-browser-hint-background: #e3e7ea !default;
    $wd--login-browser-hint-icon-color: $wd--login-browser-hint-color !default;
