### ISSUE TITLE
Cookie-Einstellungen werden erst nach Login angezeigt

### ISSUE THREAD

**Issue by ChristinaGu** [wirDesign-communication-AG/wirHub-doc#104]
Der Navigationpunkt "Cookie-Einstellungen" wird erst nach Login angezeigt, obwohl wir das Analytics-Snippet und den Consent-Banner schon auf der Login-Seite eingebaut haben. 

Betrifft 
https://www.markenportal-versicherungskammer.de/

Bitte fixen.

**Comment by pmdevelopment** [comment]
Ursache: auf der Login ist die Footer Navigation unter einem abweichenden Pfad.

**Comment by pmdevelopment** [comment]
Das Problem ist gelöst.
