### ISSUE TITLE
Spaceübergreifende Suche

### ISSUE THREAD

**Issue by ChristinaGu** [wirDesign-communication-AG/wirHub-doc#114]
Es soll eine spaceübergreifende Suche geben, die sowohl in der Navigation der Space-Übersichtseite als auch optional auf der Space-Übersichtseite  unter der Bühne platziert werden können soll. 

V**-21261A / 3

**Comment by ChristinaGu** [comment]
**Schritt 1:**
Analog zum News-Feature, wird das bestehende Ergebnis der Schnellsuche um den jeweiligen Space Titel ergänzt. 

**Schritt 2:** 
Übergreifende erweiterte Suche, siehe https://vkb-staging.wirhub.de/versicherungskammer-bayern/search?query=versal mit Tabs

**Comment by pmdevelopment** [comment]
Für die Suche als SmartBlock gibt es bisher kein Design?

**Comment by pmdevelopment** [comment]
@ChristinaGu es gibt kein Design für die Suche oben in der Titel-Leiste auf dem Dashboard, daher hab ich es mal im Stil der News/Einstellungen gemacht: 

![2022-01-03 (1)](https://user-images.githubusercontent.com/4947485/147952023-c131500b-8fe8-4951-a714-98b1dd3b1441.png)

Kann ich das so umsetzen? Das bisherige Design funktioniert dort meiner Meinung nach nicht mehr und wird auch in Zukunft mit der geänderten Navigation nicht mehr funktionieren, dabei könnten wir dort dann ebenfalls die oben gezeigte Stilrichtung übernehmen.

**Comment by ChristinaGu** [comment]
Design bitte wie besprochen wie bei https://www.allianz.de/

Langfristig sollte Navigation überall aussehen wie bei Space-Overview (natürlich ggf. mit Ergänzung von Breadcrumb)
