### ISSUE TITLE
SmartBlocks Icons: Erweiterung um Kategorie, Collections und Tags

### ISSUE THREAD

**Issue by ChristinaGu** [wirDesign-communication-AG/wirHub-doc#117]
Das SmartTool Icons, soll um die folgenden Features erweitert werden. 

*JPG*
- [x] Das Format JPG soll entfernt werden

**Suche**
- [x] Die Suche soll prominenter platziert werden
- [x] Nutzer können zukünftig über Freitext, Tags oder Collections suchen
- [x] Die meistgesuchten Tags werden unter der Suche angezeigt 
- [x] Als erstes Tag wird "Neuste" bzw. "Newest" angezeigt. Damit werden Icons gefiltert, die in den letzten 14 Tagen hochgeladen wurden
- [x] Klickt der Nutzer auf einen der Tags, werden ihm nur Icons mit diesem Tag angezeigt
- [x] Unter der Suche werden die Collections angezeigt. Diese werden alphabetisch sortiert. Angezeigt werden nur die ersten beiden Collections. Gibt es mehr, sind diese ausklappbar

**Suchergebnis**
- [x] Das Suchergebnis wird nach Kategorien geclustert. 
- [x] Neben dem Kategorienamen steht die Anzahl, der in der Kategorie enthaltenen (bei aktivierten Tags oder Collections natürlich die in der Kategorie mit dem Tag bzw. in der Collection enthaltenen) Icons.
- [x] Gibt es mehr als 12 Icons in einer Kategorie passend zu der Suche, wird eine Pagination eingeführt

**Kategorien**
Einzelne Icons, können nach Upload einer Kategorie zugewiesen werden. Ein Icon kann dabei nur in einer Kategorie sein.
- [x] Verwaltung Kategorien: Kategorien hinzufügen, löschen, umbenennen
- [x] Wenn eine Kategorie gelöscht wird, werden die dazugehörigen Icons nicht gelöscht
- [x] Eine Kategorie besteht aus "Name" (Pflicht), "Hinweis" und "Farben" (in die Icons in der Kategorie eingefärbt werden dürfen)

**Collections**
Einzelne Icons können Collections zugewiesen werden. Ein Icon kann dabei mehreren Collections zugewiesen sein. 
- [x] Verwaltung Collections: Collection hinzufügen, löschen, umbenennen
- [x] Wenn eine Collection gelöscht wird, werden die dazugehörigen Icons nicht gelöscht
- [x] Eine Collection besteht aus "Name"
- [x] Collections können als ZIP heruntergeladen werden.
- [x] Das ZIP enthält die 4 Ordner SVG, EPS, AI, PNG in denen alle Icons aus der Collection in dem jeweiligen Dateiformat liegen
- [x] Das ZIP hat den Namen >collectionname<.zip

**Tags**
Icons können mehrere Tags zugewiesen werden.
- [x] Verwaltung Tags: Tag hinzufügen, löschen, umbenennen
- [x] Wenn eine Tag gelöscht wird, werden die dazugehörigen Icons nicht gelöscht

**Icon-Upload**
- [x] Icons können in der Icon-Übersicht oder in einem Kategorie-View hochgeladen werden
- [x] Neue Icons erhalten für 14 Tage das Label "Neu" bzw. "New"
- [x] Wird ein Icon in der Icon-Übersicht hochgeladen, hat es zunächst keine Kategorie
- [x] Icons ohne Kategorie werden ganz oben, ohne Headline, angezeigt
- [x] Wird ein Icon in einer Kategorie-Übersicht hochgeladen, wird es automatisch der Kategorie zugeordnet

**Icon bearbeiten**
- [x] siehe https://share.goabstract.com/6503869d-7fd5-4d43-b006-ee48394a411a?collectionLayerId=7944acde-68ae-47ce-9aab-a624a42b8258&mode=design&sha=bbdc19457836a50a0a38504e09c05aa25117421e

**Design**
https://share.goabstract.com/6503869d-7fd5-4d43-b006-ee48394a411a

**Redmine**
#6722

 K**-21120 / 7

**Comment by ChristinaGu** [comment]
- [ ] Die Top 10 Tags werden in der Verwaltung festgelegt. Die Tags die ganz oben in der Tabelle stehen werden angezeigt. 
- [ ] Die Suche durchsucht Name, Beschreibung und Tags der Icons
- [ ] Die Suche durchsucht Collection-Name und Beschreibung
- [ ] Im Backend werden alle Kategorien inkl. Dropzone angezeigt, damit neue Icons hinzugefügt werden können. Im Frontend werden nur Kategorien angezeigt, die mindestens ein Icon enthalten
- [ ] Bei den Suchergebnissen werden ebenfalls nur Kategorien angezeigt, die mindestens ein Suchergebnis enthalten

**Comment by karatektus** [comment]
- [ ] Löschen vom Smartblock Checken

**Comment by ChristinaGu** [comment]
Ziehe die noch offenen Punkte in ein neues Ticket um. Sven merged diesen Stand.

**Comment by pmdevelopment** [comment]
Merged und deployed
