### ISSUE TITLE
Space-Overview: Bühne

### ISSUE THREAD

**Issue by ChristinaGu** [wirDesign-communication-AG/wirHub-doc#121]
- [x] Als Editor möchte ich auf der Space-Overview eine Bühne anlegen können
- [x] Die Bühne besteht aus Hintergrund Bild oder Video und Text (MDE)
- [x] Option zum aktivieren / deaktivieren "Meistbesuchte Seiten" (siehe #115)

**Design**
Desktop
https://share.goabstract.com/3a8b8b7b-3957-4b21-83b9-8693436510f1?collectionLayerId=3d6bec2c-6423-4f76-ae5c-f09af0f6ac18&mode=design

Tablet
https://share.goabstract.com/3a8b8b7b-3957-4b21-83b9-8693436510f1?collectionLayerId=19803d5c-9316-44d6-afee-6615c0aea596&mode=design

Mobil
https://share.goabstract.com/3a8b8b7b-3957-4b21-83b9-8693436510f1?collectionLayerId=ac8e4f58-8384-42fd-90dc-ea9200db63cf&mode=design

V**-21261A

**Comment by pmdevelopment** [comment]
Meistbesuchte Seiten lagern wir komplett zu #115 aus
