### ISSUE TITLE
Space-Overview: Kacheln

### ISSUE THREAD

**Issue by ChristinaGu** [wirDesign-communication-AG/wirHub-doc#122]
- [x] Space besteht aus Bild und Text, wobei Text optional angezeigt werden kann
- [x] Reihenfolge kann bestimmt werden
- [x] Editor kann wählen, welche Spaces angezeigt werden sollen und welche nicht
- [x] Animation on hover, bitte wie bei https://www.vkb.de/content/ueber-uns/unternehmen/geschaeftsbericht/kurzportrait-konzern/ (Zahlen, Daten, Fakten)

Design
https://share.goabstract.com/3a8b8b7b-3957-4b21-83b9-8693436510f1?collectionLayerId=3d6bec2c-6423-4f76-ae5c-f09af0f6ac18&mode=design

V**-21261

**Comment by ChristinaGu** [comment]
Beim anlegen des Spaces, lade ich ja schon ein Logo hoch. Ich würde erwarten, dass er dieses Logo übernimmt, wenn ich beim platzieren des Spaces kein anderes Bild hochlade. Gerade ist die Kacheln dann einfach weiß ohne Bild. 

Bug oder Feature?

**Comment by pmdevelopment** [comment]
Nicht definiert gewesen, aber lässt sich natürlich problemfrei integrieren
