### ISSUE TITLE
Space-Overview: Ansprechpartner

### ISSUE THREAD

**Issue by ChristinaGu** [wirDesign-communication-AG/wirHub-doc#127]

**Comment by pmdevelopment** [comment]
@ChristinaGu für die Ansprechpartner brauchen wie ebenfalls das Spalten-Modul. Temporär habe ich das so umgesetzt:

![2021-12-31 (1)](https://user-images.githubusercontent.com/4947485/147822540-404c1803-f253-4706-9be3-7590495af17a.png)
 
Hier wäre es doch ganz nett, wenn wir noch piktogramme in den Buttons hätten, nicht?

**Comment by pmdevelopment** [comment]
@ChristinaGu noch eine Thematik: das Design weicht von unserem aktuellen Design ab, müssen wir hier eine Design-Weiche integrieren oder bleiben wir beim bestehenden Design?

**Comment by pmdevelopment** [comment]
Die offenen Punkte werden in #184 behandelt.
