### ISSUE TITLE
Space-Overview: Logo Leiste

### ISSUE THREAD

**Issue by ChristinaGu** [wirDesign-communication-AG/wirHub-doc#129]
Alternativ einfach Bild mit all den Optionen zur Verfügung stellen? Dann könnte die Leiste als ein Bild hochgeladen werden und wir hätten einen SmartBlock mehr auf der Startseite zur Verfügung.

**Comment by pmdevelopment** [comment]
Wie vorgeschlagen erfolgt die Lösung über den SmartBlock "Image".
