### ISSUE TITLE
SmartBlock Columns: Flexbox Option

### ISSUE THREAD

**Issue by ChristinaGu** [wirDesign-communication-AG/wirHub-doc#13]
Die Spalten sollen um eine Flexbox Option erweitert werden. 

Bitte
- Layout > Größe umbenennen in "Anzahl Spalten"
- Abstand zwischen den Spalten zu Dropdown umbauen 
- Darunter Checkbox: "Spalteninhalt auf gleiche Höhe setzen"

Außerdem bei der Gelegenheit die Anzeige der Farboptionen fixen (aktuell bei zweiter Reihe kein Abstand)

**Jobnummer**
2WD

**Comment by pmdevelopment** [comment]
- Die Einstellung sorgt dafür, dass Text-Inhalte auf die gleiche Länge gestretcht werden
- Ein Hinweis erklärt den eingeschränkten Nutzen der Funktion.
