### ISSUE TITLE
SmartBlock Stage: Feature Meistbesuchte Seiten auch außerhalb von Space-Overview

### ISSUE THREAD

**Issue by ChristinaGu** [wirDesign-communication-AG/wirHub-doc#130]
Siehe #115 

Bisher ist es nur bei einer Installation mit Spaces auf dem Space Overview möglich eine Bühne mit den persönlichen meistbesuchten Kapitel anzuzeigen.  Die Bühnen-Module sollte für das Dashboard und Unterseiten ebenfalls angepasst werden, sodass das Modul auf jedem Seitentyp die gleichen Funktionen und die gleiche UI hat.

Denkbar wäre als alternative den SmartBlock umzubenennen in Bühne (smart) und auf dem Dashboard und Unterseiten beide SmartBlocks anzubieten

**Comment by pmdevelopment** [comment]
@ChristinaGu die Stage innerhalb der Kategorien kennt ein Feature, das auf dem Dashboard bisher fehlt: `Wiedergabe: Video in einem Dialog öffnen`

Entfällt das Feature oder soll es in die Optionen integriert werden?

**Comment by ChristinaGu** [comment]
Da es nirgends Verwendung findet, kann es entfallen
