### ISSUE TITLE
SmartBlock Akkordeon: Interne  Verknüpfung funktionieren nicht

### ISSUE THREAD

**Issue by ChristinaGu** [wirDesign-communication-AG/wirHub-doc#14]
Setzt man einen Link zu einer Sprungmarke auf der gleichen Seite und der Nutzer klickt auf diesen Link, wird erst zur Sprungmarke gescrollt, aber danach wieder zurück zum Akkordeon. 

z.B. hier https://www.markenportal-versicherungskammer.de/versicherungskammer-bayern/style/category/bewegtbild-neu

Unter "Videovorlagen" im ersten Akkordeon-Item in der Hinweisbox. 

Außerdem scheinen die Sprungmarken bei den internen Verknüpfungen nicht zu funktionieren. Es scheint als zeige er Einträge doppelt und oder gelöschte Einträge. 

<img width="935" alt="Bildschirmfoto 2021-02-19 um 08 31 20" src="https://user-images.githubusercontent.com/8007132/108472397-f8cb6800-728c-11eb-8348-aa6c2f62540f.png">

**Comment by pmdevelopment** [comment]
Ursache war das "Remember" des geöffneten Accordion. Lösung: Bei  Aufruf eines Shortlinks wird das letzte Accordion vergessen.
