### ISSUE TITLE
Reihenfolge ändern funktioniert nicht

### ISSUE THREAD

**Issue by ChristinaGu** [wirDesign-communication-AG/wirHub-doc#140]
Auf dieser Seite (Englisch)
https://brandnet.kws.com/default/style/category/illustration-library

Ist das Accordion "Download - Illustration Kit" als Alias angelegt. 

Das Original liegt hier
https://brandnet.kws.com/default/style/category/illustration-style

Wenn ich auf der ersten Seite versuche die Position des Akkordions zu verschieben funktioniert das zwar. Nachdem die Seite neu geladen wird, steht der SmartBlock aber auf einer anderen Position. Egal ob er via Toolbar oder Quick Edit verschoben wird. Wir haben das Element auch schon gelöscht und komplett wieder neu angelegt. 

Es scheint ein Problem bei der Kombination aus Akkordion und Alias mit dem Verschieben zu geben.

**Comment by ChristinaGu** [comment]
siehe #6846 in Redmine

**Comment by pmdevelopment** [comment]
Aliases lassen sich derzeit nicht verschieben.
