### ISSUE TITLE
Schnelles Bearbeiten - Innenabstand nicht auswählbar

### ISSUE THREAD

**Issue by laurahll** [wirDesign-communication-AG/wirHub-doc#147]
Wenn man beim Innenabstand den unteren Abstand auswählt, liegt das Popup hinter der weißen Fläche.
![image](https://user-images.githubusercontent.com/66866462/141808676-d116ed00-185e-4fba-9818-799160bc42a7.png)

**Comment by laurahll** [comment]
Google Chrome Version 95.0.4638.69 (Offizieller Build) (x86_64)

**Comment by ChristinaGu** [comment]
Kann bei gleicher Chrome Version nicht reproduzieren.

**Comment by ChristinaGu** [comment]
Ich kann es nur bei AUSSENABSTAND Unten reproduzieren. Nicht bei Innenabstand. Ist es bei dir wirklich Innenabstand @laurahll

**Comment by ChristinaGu** [comment]
schließe ich, da Duplikat von #188
