### ISSUE TITLE
SmartBlocks: Option > Link um Space-Auswahl erweitern

### ISSUE THREAD

**Issue by laurahll** [wirDesign-communication-AG/wirHub-doc#148]
Bitte die folgende SmartBlocks unter Bearbeiten > Optionen > Link um eine Space-Auswahl erweitern. Space-Auswahl sollte analog zu internem Link im MDE funktionieren: 

- [x] Bild
- [x] Teaser
- [x] Call-To-Action
- [x] News

**Status-Quo**
![image](https://user-images.githubusercontent.com/66866462/141984336-c160121c-d8c5-4264-a1a5-0abbbb48f129.png)

**Zielbild**
![image](https://user-images.githubusercontent.com/66866462/141984597-ae60288f-e754-42ee-b47b-e7d521c67927.png)

**Job**
V**-21261

**Comment by pmdevelopment** [comment]
Die Lösung für Smartblocks sieht wiefolgt aus: der Tab "Link" auf der Bearbeitungsseite verschwindet; die Elemente werden ausnahmslos "quick" hinzugefügt; die Verlinkung wird per Inline-Toolbar verwaltet.
