### ISSUE TITLE
SmartBlock Teaser: Video nicht auswählbar

### ISSUE THREAD

**Issue by laurahll** [wirDesign-communication-AG/wirHub-doc#149]
Hat man sich einmal für einen Bild-Teaser entschieden, kann dieser nachträglich nicht zu einem Video-Teaser geändert werden. 

- [ ] Switch zwischen Bild und Video möglich
- [ ] Controls sollten bei Video optional ausgeblendet werden können und Video sollte optional im Loop abgespielt werden können, siehe SmartBlock Video

**Comment by ChristinaGu** [comment]
Das Problem ist nicht, dass das Video nicht ausgewählt werden kann. Man kann nachträglich die Auswahl nicht mehr ändern. Beim Anlegen entscheidet man sich ob Video oder Bild.

**Comment by laurahll** [comment]
Ich wollte das Layout eines Text-Moduls ändern und kann da auch nicht mehr switchen. gleicher fehler? @ChristinaGu 
![image](https://user-images.githubusercontent.com/66866462/142200708-5539d807-688c-4d54-a084-5cd91bfc3138.png)
