### ISSUE TITLE
SmartBlocks: Tab Layout optimieren

### ISSUE THREAD

**Issue by ChristinaGu** [wirDesign-communication-AG/wirHub-doc#16]
- [x] "Abstand von Innen" umbenennen in "Innenabstand"
- [x] "Abstand von Außen" umbenennen in "Außenabstand"
- [x] Einstellungen für Links & Rechts für Innenabstand und Außenabstand entfernen 

Wurde diese Option bei einem SB verwendet, bleiben die Klassen dafür im Tagging erhalten. 
Wird ein betroffener SB geändert und gespeichert, bleiben die Klassen ebenfalls erhalten. 

Bei Bedarf erweitern wir die Toolbar zu einem späteren Zeitpunkt um eine Funktion die alten Einstellungen für Padding/Margin Links/Rechts zu entfernen.

**Comment by pmdevelopment** [comment]
Timing kann nicht gehalten werden, auf den nächsten Release verschoben.
