### ISSUE TITLE
v2.3.10: offene Bugs und Verbesserungen

### ISSUE THREAD

**Issue by ChristinaGu** [wirDesign-communication-AG/wirHub-doc#160]
**News**
- [x] Sortieren noch defekt sobald das Akkordeon einmal geöffnet wurde (auch wenns wieder zu gemacht wird)
- [x] SimpleMDE internal link tut nich
- [x] Bei Hinzufügen von neuer News, Akkordeon öffnen

**Sonstiges**
- [x] Globales Kontaktformular wird nicht angezeigt
- [x] Nutzer-Menü schon auf Space-Übersicht
- [x] SmartBlock Anmerkungen: Drop-Zone funktioniert nicht / Hochladen ebenfalls nicht möglich
- [x] Footer: Klick auf "Hilfe" im Footer wirft schwerwiegenden Fehler
- [x] SmartBlock Do/Don't: Eintrag hinzufügen nicht möglich
- [x] SmartBlock Bühne: Obwohl Default "Art = Bild" ausgewählt ist, wird initial Dropzone für Bild UND Video angezeigt

**Comment by pmdevelopment** [comment]
@ChristinaGu: wenn ich eine News speichere, sollte sich dann nicht das accordion schließen und eine Success snackbar erscheinen?
