### ISSUE TITLE
SmartTool: Media Creator

### ISSUE THREAD

**Issue by ChristinaGu** [wirDesign-communication-AG/wirHub-doc#161]
Banner- und Posting-Creator werden zu einem Creator zusammengefasst. Gleichzeitig werden die neuen Simplification Regeln eingearbeitet. 

**Design**
https://share.goabstract.com/41f4f38a-a8a0-4450-a140-8a82fb551da4

**Zugehörige Redmine Tickets**
#6920
#6949

K**-21095 / 5

**Comment by pmdevelopment** [comment]
@ChristinaGu ich benötige die Auswahlbilder von "MediaCreator/Banner/Overview" als Assets.

**Comment by ChristinaGu** [comment]
[Assets-SVG.zip](https://github.com/wirDesign-communication-AG/wirHub-doc/files/7602075/Assets-SVG.zip)

**Comment by pmdevelopment** [comment]
Bitte ein mal nur den Claim: [source_without_shadow.zip](https://github.com/wirDesign-communication-AG/wirHub-doc/files/7609148/source_without_shadow.zip)
