### ISSUE TITLE
Navigation: Space-Switch

### ISSUE THREAD

**Issue by ChristinaGu** [wirDesign-communication-AG/wirHub-doc#163]
*Design*
https://share.goabstract.com/354141e6-c66d-4bd9-8e1b-a60cc1906a19?collectionLayerId=0233ad8d-bde1-4459-b160-ad4a98870b33&mode=design&sha=latest

bzw.

https://share.goabstract.com/354141e6-c66d-4bd9-8e1b-a60cc1906a19?collectionLayerId=0bf23c4c-03ed-4221-9462-f19d02c7a97b&mode=design&sha=latest

**Comment by pmdevelopment** [comment]
Feedback bitte in #184
