### ISSUE TITLE
QuickEdit: Feedback verdeckt Außenabstand

### ISSUE THREAD

**Issue by laurahll** [wirDesign-communication-AG/wirHub-doc#166]
Das Feedback-Overlay liegt über dem QuickEdit Menu. Das Design Support Overlay verschwindet jedoch dahinter. Ich kann dadurch diese Verlinkung des oberen und unteren Abstandes nicht einstellen.
@ChristinaGu kannst du das reproduzieren, wie bei dem letzten Mal beim inneren Abstand? (Bei KWS kann man es übrigens besser sehen)
![image](https://user-images.githubusercontent.com/66866462/143249254-f0928da1-4286-412a-903a-a63efc9bfb4b.png)
![image](https://user-images.githubusercontent.com/66866462/143249642-445a2374-e9b5-4c2c-ae45-17bf3dc0603e.png)

**Comment by ChristinaGu** [comment]
Darauf haben wir leider keinen Einfluss, da das Feedback-Formular über Javascript, auf das ich keinen Einfluss habe, extern eingebunden wird.

Wenn es dich beim Bearbeiten stört: Feedback-Formular einmal öffnen und schließen. Dann verschwindet es.
