### ISSUE TITLE
SmartBlock Text & Teaser: Doppeltes Textfeld

### ISSUE THREAD

**Issue by laurahll** [wirDesign-communication-AG/wirHub-doc#169]
Der Text Input im Bearbeitenmodus wird doppelt angezeigt.
Ich hab den Bug erst beim Teaser Modul entdeckt, scheint aber alle Module mit Text zu betreffen.

![image](https://user-images.githubusercontent.com/66866462/143565852-f9933621-5a6b-4597-a752-ffc2773fbd58.png)
![image](https://user-images.githubusercontent.com/66866462/143565767-0a64ffb8-ea3e-4228-b51c-e07b8af0bbdc.png)

**Comment by pmdevelopment** [comment]
Welcher VKB wirHub ist das? v2.3.11 Staging Branch sollte das Problem nicht mehr haben, eventuell muss man den aktualisieren

**Comment by laurahll** [comment]
Das ist der VKB staging hub - v2.3.8-1
aktualisieren wäre dann wohl gut.

**Comment by ChristinaGu** [comment]
update erledigt. fehler scheint behoben zu sein

**Comment by laurahll** [comment]
@ChristinaGu Wenn man ein neues Modul anlegt ist der Fehler verschwunden, bei alten Modulen ist der Fehler noch da.

**Comment by pmdevelopment** [comment]
Könnt ihr das mal auf vkb-acceptance versuchen zu reproduzieren? Dort ist ein neuerer Stand online

**Comment by laurahll** [comment]
Ich kann es dort nicht reproduzieren. Nicht bei alten oder neuen Modulen. 
Kann das irgendwie an den vor dem Update erstellten Modulen liegen?

**Comment by pmdevelopment** [comment]
Das liegt daran, dass ich den Bug dann schon erfolgreich behoben habe ;) Acceptance ist der neuste Beta-Stand, mit dem nächsten Release kommt da der Fix zu Staging.
