### ISSUE TITLE
SmartBlock Spalten: Gleiche Abstände setzen 

### ISSUE THREAD

**Issue by laurahll** [wirDesign-communication-AG/wirHub-doc#170]
Sehr spezifischer Bug. Ich hab ein neues Spaltenmodul angelegt und kann die Abstände nicht "verlinken". Wenn ich auf das Icon in der Mitte zwischen den Dropdowns klicke, tut sich nichts.
Abstände im Quick-Edit Mode funktionieren und wenn ich mit dem gleichen Modul nach dem Speichern nochmal in die Bearbeitenansicht springe, geht es auch.
in vkb-staging auf v2.3.10
![image](https://user-images.githubusercontent.com/66866462/143601960-37f794b4-d7af-44f7-9b6e-b1ac65e445e6.png)

**Comment by ChristinaGu** [comment]
Obwohl ein Bug, packe ich den mal in den Backlog, da man den Fehler im Moment über den Quick-Edit auch gut umgehen kann und wir einfach zu viel zu tun haben. Würde mich darum kümmern, sobald es wieder etwas ruhiger wird.

**Comment by pmdevelopment** [comment]
Ist der Bug noch aktuell? Ich kann ihn nicht reproduzieren.

**Comment by laurahll** [comment]
Nein, scheint sich erledigt zu haben.
