### ISSUE TITLE
wirHub Administration optimieren

### ISSUE THREAD

**Issue by laurahll** [wirDesign-communication-AG/wirHub-doc#171]
Sollte hier neben dem Speichern Button nicht eigentlich noch ein Abbrechen Button stehen?
Wenn ich auf so einer Seite über den Browser zurück gehe, hab ich immer das Gefühl irgendwas kaputt zu machen 😂@ChristinaGu 
![image](https://user-images.githubusercontent.com/66866462/143605138-ce1cf4fb-f861-41d3-a0fd-744be5c694fd.png)

**Comment by ChristinaGu** [comment]
Allgemein, müsste man aus meiner Sicht diesen ganzen Bereich mal optimieren. Navigation sollte überarbeitet werden. Das fängt mit so Kleinigkeiten an wie 
"Farben" zu "Farben verwalten" oder das der Bereich "Funktionen" mittlerweile ganz schön unübersichtlich ist. Der Punkt "Einstellungen" sollte eig komplett verschwinden und an sinnvollen Stellen verteilt werden. Es handelt sich hier ja bei Allem um Einstellungen. 

Auch der Umgang mit Breadcrumb und Portlet Title und das da 2x Einstellungen und 2x Bearbeiten steht, stört mich schon lange. Meiner meinung nach könnte z.B. der Portlet Title entfallen. Das ist die Headline über "Titel der Seite", aber auch das "Einstellungen" neben der Breadcrumb könnte evtl. weg

Das  müsste man aber alles mal in einem Ticket zusammenfassen und evtl. hier und da auch nochmal Designs liefern.

**Comment by pmdevelopment** [comment]
Ergibt sich der Wegfall der Portlets nicht aus dem neuen Nav-Design?
