### ISSUE TITLE
SmartBlock Bild: Unendliches Laden

### ISSUE THREAD

**Issue by laurahll** [wirDesign-communication-AG/wirHub-doc#173]
Wenn ich ein Bild in VKB-staging(v2.3.10) hochlade, endet die Ladeanimation nicht mehr. Wenn ich die Seite neu lade, scheint aber alles ok zu sein.
![image](https://user-images.githubusercontent.com/66866462/143838820-98e6d65a-a615-4813-ad9c-f76125c2d752.png)

**Comment by ChristinaGu** [comment]
Wichtig ist hier immer: wo und wie lädst du das Bild genau hoch? Also per Drag&Drop in die Dropzone auf der Seite oder unter Bearbeiten in die Dropzone. Oder über den Finder?

Außerdem wäre ein Hinweis gut, ob das bei jedem Bild passiert oder nur bei besonders großen Bildern. 

Gerne Hinweise ergänzen und dann unter v2.3.12 in Bug-Liste ergänzen und Sven zuweisen.

**Comment by laurahll** [comment]
Wenn man das Modul hinzufügt, kann man beim ersten Mal ja direkt auf der Seite hochladen ohne in den Bearbeitenmodus zu gehen. Ich hab es so über den Finder hochgeladen.
Der Bug tritt bei mir unabhängig vom Format auf, egal ob jpg,svg etc. Aber immer nur beim Bild modul.

Chrome 96.0.4664.55 (Offizieller Build) (x86_64)

**Comment by ChristinaGu** [comment]
Lässt sich reproduzieren

**Comment by ChristinaGu** [comment]
Schließe ich, da Fehler wie den Javascript Fehlermeldungen zu entnehmen ist mit dem Sprungmarken Bug zusammen hängt. Siehe #26
