### ISSUE TITLE
SmartBlock Animation: Abstand bei voller Breite entfernen

### ISSUE THREAD

**Issue by laurahll** [wirDesign-communication-AG/wirHub-doc#174]
@ChristinaGu Ich hab gerade mit Caro nochmal den grundsätzlichen Aufbau jeder Seite im Markenportal besprochen und wir würden gerne doch mehr die Bühne benutzen. Wäre es möglich recht fix in dem Modul auch Lottie Animationen zu erlauben? Wäre super hilfreich

**Comment by ChristinaGu** [comment]
Bis zum 10.01. nicht, aber ihr könnt es ja erstmal als Video einbauen und wir optimieren es dann danach.

**Comment by laurahll** [comment]
In der Bühne brauchen wir Lottie doch nicht wirklich. 
Man kann das Animation-Modul ja schon auf die volle Breite einstellen, aber es gibt dann immer noch oben zum Seitenanfang einen kleinen abstand. Ich glaube das Bühnen Modul hat immer ein margin-top: -2.2rem; damit es oben am Rand liegt. Könnten wir das bei der Animation auch hinkriegen. Vielleicht eine checkbox beim layout? @ChristinaGu @pmdevelopment 
![image](https://user-images.githubusercontent.com/66866462/144085958-d74c4983-3cf0-4daa-b302-04f8b1f0409c.png)

**Comment by ChristinaGu** [comment]
Haben wir mittels custom.scss gelöst
