### ISSUE TITLE
Frontend: Styles nicht überschreibbar

### ISSUE THREAD

**Issue by laurahll** [wirDesign-communication-AG/wirHub-doc#176]
Es gibt ein paar Styles, die man nicht überschreiben kann. Bitte entfernen (angeblich in styleguide.min.css)

Die Kapiteltrenner im Sidemenu sollen wieder Margin-Top haben:
.m-aside-menu .m-menu__nav .m-menu__section.m-menu__section--first {
    margin-top: 0 !important;
}

Beim Hover-Zustand des Primary Button ist die Schrift weiß:
.btn.btn-primary.active, .btn.btn-primary.focus, .btn.btn-primary:focus, .btn.btn-primary:hover:not(:disabled) {
    color: #ffffff !important;
}

@ChristinaGu Hab ich noch was vergessen von gestern?

**Comment by pmdevelopment** [comment]
Man kann styles immer überschreiben, man muss es nur richtig machen ;)

**Comment by laurahll** [comment]
Glaube ich dir sofort. Bei den beiden hilft nur sogar !important nicht mehr. 
Wie könnte man die noch überschreiben?

**Comment by pmdevelopment** [comment]
Normalerweise müsste es so funktionieren:

```
html .m-aside-menu .m-menu__nav .m-menu__section.m-menu__section--first {
margin-top: 20px !important;
}
```

Es funktioniert nur nicht, wenn am Element selbst über `style="margin-top:0!important"` der Wert gesetzt wird.

**Comment by laurahll** [comment]
Gibt es einen Grund für solche Inline-styles? Kann man doch eigentlich in dem Frontend Editor im wirHub selbst machen

**Comment by pmdevelopment** [comment]
Normalerweise sollte es keine Inline-Styles geben, lediglich wenn Elemente per Script gebaut werden ist das in Ordnung. Sollte aber sehr selten nur vorkommen.

**Comment by ChristinaGu** [comment]
gelöst
