### ISSUE TITLE
SmartBlock DoDont: Modul verschwindet

### ISSUE THREAD

**Issue by laurahll** [wirDesign-communication-AG/wirHub-doc#179]
Wenn ich das Do Dont Modul auf dieser Seite anlege https://vkb-staging.wirhub.de/versicherungskammer-bayern/style/category/logo (v2.3.10) und es ganz normal befülle, verschwindet es beim Neuladen der Seite einfach.

**Comment by pmdevelopment** [comment]
@ChristinaGu bitte validier das.

**Comment by ChristinaGu** [comment]
Kann ich nicht reproduzieren. Wie du sehen kannst konnte ich das Modul am Ende der Seite ganz normal anlegen. 

Bitte Bugs genau verifizieren. Bitte bei sowas auch gerne die Assets mit anhängen, die du versucht hast du verwenden und genau beschreiben, was du getan hast. Wie viele Einträge wurden angelegt? Mit Beschreibung oder ohne? Welche Assets? 

Ich habe keine Zeit nicht vorhandenen Bugs hinterher zu jagen.

**Comment by laurahll** [comment]
![image](https://user-images.githubusercontent.com/66866462/146150900-62a77eed-7a7e-47ae-a0c0-bb909704aad5.png)
Und warum liegen dann 4 leere Smartblocks Container zwischen der Headline und dem von dir angelegten Do Dont Modul. 
ich hab es nicht genauer angegeben, weil es egal war, was für BIlder oder Texte ich dazu geschrieben habe. 

Dein Block ist übrigens jetzt wieder weg

**Comment by laurahll** [comment]
ich benutze Chrome Version 96.0.4664.93 (Offizieller Build) (x86_64). Aber Fehler tritt bei mir mit PNGs oder SVGs auf. Bei Do und Dont Auswahl. Einfach egal was ich einstelle

**Comment by ChristinaGu** [comment]
Ich kann es auch mit SVGs und PNGs nicht reproduzieren. Schick mir doch mal bitte die Dateien, mit denen du es versuchst.

**Comment by laurahll** [comment]
Welche von den 10 verschiedenen dateien soll ich schicken :D ich hab an deinem Modul auch nichts geändert und es ist trotzdem verschwunden.
![VKB_Markenportal_Basics_platzhalter_Basis_2Columns_high_718x500-03](https://user-images.githubusercontent.com/66866462/146177174-3e1206cb-5bf8-4097-ae42-12b67ed6355d.jpg)

**Comment by laurahll** [comment]
Wie kriegen wir die leeren Smartblock da überhaupt wieder raus?

**Comment by laurahll** [comment]
Sind sie jetzt einfach wieder da?

**Comment by ChristinaGu** [comment]
geht es jetzt? habe etwas an den berechtigungen der ordner angepasst. ich glaube man konnte bilder hochladen, hatte aber keine berechtigung auf dem server zu speichern. deswegen waren sie dann nach reload der seite weg. müsste behoben sein?!

**Comment by laurahll** [comment]
Ja ich sehe jetzt wieder alle

**Comment by laurahll** [comment]
@ChristinaGu Irgendwas stimmt immer noch nicht mit den rechten. Hab folgendes gemacht:
1. Smartblock erstellt und befüllt.
2. Seite neu geladen -> Block ist noch da
3. im Quick Edit Modus die Abstände bearbeitet
4. Seite neu laden -> Block ist wieder leer/weg!

**Comment by laurahll** [comment]
@pmdevelopment hat dir Christina schon bescheid gesagt, woran der Bug liegen sollte? Wir wollen die Seite bald duplizieren. Wäre super, wenn es nächste Woche wieder funktioniert.

**Comment by pmdevelopment** [comment]
Es gab ein Problem mit mit Ordner-Rechten, das hab ich gelöst und einen Test gestartet(https://vkb-staging.wirhub.de/konzern-versicherungskammer/style/category/test-intern) um zu verifizieren, dass der Block nicht verschwindet.

**Comment by laurahll** [comment]
Scheint noch nicht ganz funktioniert zu haben. Ich hab die gleichen Aktionen auf vkb-staging (v2.3.11-1) gemacht wie bei meinem vorletzten Kommentar und ein neuer Do Dont Smartblock ist wieder weg.
Den fehler hatte Christina eigentlich auch schon gelöst. Stellt der sich von selbst wieder ein? Ich würde den Smartblock dann erstmal nicht mehr benutzen.

Gibt es eine Möglichkeit die unsichbaren smartblocks zu entfernen? 
https://vkb-staging.wirhub.de/versicherungskammer-bayern/style/category/logo
Auf dieser Seite liegen nach der Headline "Unerlaubte Verwendung" jetzt 4 unsichtbare Do/Donts

**Comment by pmdevelopment** [comment]
Kann bestätigen der Bug ist noch da, was ein komisches Verhalten. Ich analysiere weiter.

**Comment by pmdevelopment** [comment]
Ursache: Ein Subscriber schaut beim Speichern des Moduls, welche Einträge nicht übermittelt wurden um sie zu löschen. Da beim Quick Edit keine Einträge übermittelt werden, löscht er vollständig.
