### ISSUE TITLE
Suchergebnisse nach Position in Navigation priorisieren

### ISSUE THREAD

**Issue by ChristinaGu** [wirDesign-communication-AG/wirHub-doc#18]
Als Nutzer möchte ich, dass die Suchergebnisse nach ihrer Position innerhalb der Navigation sortiert werden. 

**KWS-20049 / Digitalization Concept**

**Comment by ChristinaGu** [comment]
Wurde freigegeben.

**Comment by pmdevelopment** [comment]
Anmerkung: in dem Zuge stelle ich auch die Suchergebnisse der Elemente auf Positions um, da wichtigere vermutlich ebensfalls immer am Anfang der Seite sind. Einwände?

**Comment by ChristinaGu** [comment]
Klingt sinnvoll
