### ISSUE TITLE
Space-Overview: Feedback-Schleife

### ISSUE THREAD

**Issue by pmdevelopment** [wirDesign-communication-AG/wirHub-doc#184]
### Enhancements
- [x] Smart Block: Bühne - Videos in der Stage müssen skaliert werden
- [x] Fehlende Top-5 in Stage durch Hinweis ersetzen (Bild 1)
- [x] Meist-besuchte Seiten in der Stage brauchen den Space vorangestellt.
- [x] Per-Sie neutralisieren
- [x] Design-Verbesserung für Spalten wie in #127 erwähnt?
- [x] Design-Anpassung der Ansprechpartner wie in #127 erwähnt?
- [x] Smart-Block Kapitel Teaser: Abstand zwischen erster und zweiter Reihe muss angepasst werden
- [x] Space-Overview: Ausschneiden, Copy&Paste aktivieren
- [x] Space-Switch:  padding bitte so: `.m-aside-menu .spaces-choice { padding: 2rem 0.5rem 0 0.5rem }
`; Breite von Dropdown dementsprechend anpassen; Bei hover auf den Menüpunkt bitte Tooltip mit vollausgeschriebenen Spacen-Namen einblenden

### Bugs
- [x] Wenn ein Bild auf der Space-Overview in einem Smart-Block per Drag&Drop hochgeladen wird (z.B. im Kapitel-Teaser oder beim Ansprechpartner) wird dieses auch automatisch in der Bühne eingesetzt 

Bild 1
![cf1bca4c-57c6-4730-8cfd-a800d15b7cc6](https://user-images.githubusercontent.com/4947485/147406100-e4e72fe6-e348-4b3f-a6f6-0fbe3ddfba18.png)

**Comment by pmdevelopment** [comment]
Bug sollte in der aktuellen Beta bereits behoben sein.

**Comment by ChristinaGu** [comment]
Betrifft das dann nicht auch #193 und das Ticket kann geschlossen werden?

**Comment by pmdevelopment** [comment]
Merged, weiteres Feedback in neuem Task.
