### ISSUE TITLE
Seite für Nutzer ein- / ausblenden direkt in Seitenübersicht

### ISSUE THREAD

**Issue by ChristinaGu** [wirDesign-communication-AG/wirHub-doc#19]
Als Editor möchte ich Seiten direkt in der Seitenübersicht ein- und ausblenden können und nicht erst den Weg über "Seite bearbeiten" gehen müssen. 

Im gleichen Zug bitte die Funktion um eine neue Seite hinzuzufügen und gelöschte Seiten anzeigen zu lassen nach oben packen. 

Außerdem bitte Headline der Seite und den Navigationspunkt von "Seite" in "Seiten verwalten" bzw. "Manage pages" umbenennen. 

- [x] Funktion für Seite ein- und ausblenden
- [x] Hinzufügen und gelöschte Seite nach oben
- [x] Seite umbenennen in "Seiten verwalten"

**Comment by ChristinaGu** [comment]
Wie besprochen das vorhandene Augen-Icon in der Seitenübersicht klickbar machen. Ist eine Seite sichtbar erscheint es auf hover mit einem Tooltip "Seite ausblenden". Ist es unsichtbar erscheint auf hover der Tooltip "Seite einblenden".

Kein Dialog!

**Comment by pmdevelopment** [comment]
Notiz: "Hinzufügen" wird "Seite hinzufügen" als Primary Button oben rechts, links daneben als Link die Option zu gelöschten Seiten.
