### ISSUE TITLE
Schnelles Bearbeiten von Smartblocks logisch gestalten

### ISSUE THREAD

**Issue by pmdevelopment** [wirDesign-communication-AG/wirHub-doc#191]
Mit dem neuen Dashboard ergibt sich eine Trennung aus SmartBlock spezifischen Einstellungen und dem "schnellen Bearbeiten". Hier sollte eine einheitliche Strategie gefunden werden.

**Comment by ChristinaGu** [comment]
Wie besprochen ändern wir Quick Edit in "Einstellungen und ersetzen das Icon durch das Gear Icon. Das Gear Icon öffnet ein Dropdown mit 

(Icon Brush) Layout 
(Icon Visibility) Zugriff 
(Icon Tune) Weitere Optionen

Alle Einstellungen darüber hinaus wandern in die neue Toolbar. 

Ich schließe das Ticket daher.
