### ISSUE TITLE
SmartBlock Bild: Drag&Drop Feld im normalem Modus

### ISSUE THREAD

**Issue by laurahll** [wirDesign-communication-AG/wirHub-doc#192]
In der normalen Ansicht erscheint ein neues Drag-Drop Feld unter dem SmartBlock Bild. Im Bearbeitenmodus ist es nicht mehr zu sehen. War das so gedacht? Anders rum wäre es logischer.
VKB-Staging v2.3.11-1

![image](https://user-images.githubusercontent.com/66866462/147946346-531d34ce-abb5-4afa-a5db-015d2e659bde.png)

**Comment by pmdevelopment** [comment]
Vermutlich sogar schon im letzten Bugfix mit deployed.
