### ISSUE TITLE
SmartTool Inspirations: Share-Funktion funktioniert nicht

### ISSUE THREAD

**Issue by ChristinaGu** [wirDesign-communication-AG/wirHub-doc#2]
Es sollte möglich sein einen Beitrag über die eingebaute Share-Funktion zu teilen. 

Genau wie bei der Share-Funktion der Smart-Blocks, war es möglich einen zeitlich begrenzten Link zu erstellen, der es ermöglichen sollte einen Beitrag zu teilen. 

Im Moment lädt er endlos und es passiert nichts nach klick auf "Share"
![share-feature](https://user-images.githubusercontent.com/8007132/111767299-d7b76080-88a6-11eb-8642-987cd350b93d.png)

**Comment by pmdevelopment** [comment]
StyleBundle\Entity\Tool\Inspiration object not found by the @ParamConverter annotation.
