### ISSUE TITLE
Original eines Alias ebenfalls kennzeichnen

### ISSUE THREAD

**Issue by ChristinaGu** [wirDesign-communication-AG/wirHub-doc#20]
Als Editor möchte ich dass ein SmartBlock der Verknüpfungen in Form eines Alias besitzt ebenfalls gekennzeichnet wird. 

Die Kennzeichnung erfolgt über die Toolbar. 

Über die Toolbar soll es ebenfalls möglich sein einen Dialog auszulösen. Hier sollen alle Seiten aufgelistet und verlinkt werden, auf denen ein Alias des SmartBlocks platziert ist. Die Verlinkungen untereinander können hier gelöst werden.

Design, siehe hier 
https://share.goabstract.com/b6f26507-5d03-4f1a-9a01-45759d8ad578

**Comment by ChristinaGu** [comment]
Hi Esther - das hier war noch ein offener Punkt bei der neuen Toolbar. Das Design hierzu fehlt auch noch @estherconstantin

**Comment by estherconstantin** [comment]
Collection in Abstract aktualisiert

**Comment by pmdevelopment** [comment]
Fortsetzung in #108
