### ISSUE TITLE
SmartBlock Iconlist: Sammlung löschen

### ISSUE THREAD

**Issue by laurahll** [wirDesign-communication-AG/wirHub-doc#206]
ich wollte eine Sammlung löschen und lande auf der Error seite
![image](https://user-images.githubusercontent.com/66866462/149988935-b0fda85e-53b9-4a4f-86c5-afb3ea3f50c6.png)
![image](https://user-images.githubusercontent.com/66866462/149988983-05bae201-44a3-484a-b556-ccce7d7a293b.png)

**Comment by karatektus** [comment]
Is das noch aktuell? konnte es nich nachvollziehen, sieht nach nem bereits geklärten Problem in #201 aus?

Hab aber ne kaputte translation gefunden und die gefixt.
