### ISSUE TITLE
SmartBlock Columns: Verbesserte Toolbar

### ISSUE THREAD

**Issue by pmdevelopment** [wirDesign-communication-AG/wirHub-doc#220]
Die Inline-Toolbar für Columns lässt sich leicht verwechseln mit dem Edit eines SmartBlocks.

Wollen wir in die Inline-Toolbars jeweils das Icon des SmartBlocks integrieren? Könnte eigentlich überall Sinn machen, wo ein SmartBlock nur eine einzelne Inline-Toolbar hat. Alternative Idee wäre bei Columns statt dem Pencil dann das Columns icon zu zeigen.

**Comment by laurahll** [comment]
Ich arbeite gerade an einem Entwurf. Sollen langfristig alle Einstellungen eines Smartblocks (außer layout usw) in die Inline Toolbar? Oder wäre auch ein einzelner zusätzlicher Button in der Toolbar zu einem Pop up möglich? Bei einigen Smartblocks wie zB Slideshow gibt es viele zusätzliche funktionen, aber zB beim Bild finde ich die unterteilung nicht so praktisch. Wenn ich Text und Link bei einem Bild ändern will, muss ich quasi 2 mal seperat Öffnen, Einstellen, Speichern.
![image](https://user-images.githubusercontent.com/66866462/152761450-d2033dd6-2d95-426b-b78d-fe70a649ffb7.png)
![image](https://user-images.githubusercontent.com/66866462/152761580-4bf80300-0eb5-4286-a7db-65c722b17d07.png)
