### ISSUE TITLE
Startseite: Keine Hintergrundfarben

### ISSUE THREAD

**Issue by laurahll** [wirDesign-communication-AG/wirHub-doc#232]
Bei den Modulen auf der Startseite stehen keine Hintergrundfarben mehr zur auswahl.  vkb-staging [v2.3.12-1]
Dadurch verschwindet zB beim Hinweis die Box. Muss vor dem launch am 7. gefixed sein.
![image](https://user-images.githubusercontent.com/66866462/152325470-496a5ef4-dceb-4a4b-802f-9aa57d00b07a.png)
![image](https://user-images.githubusercontent.com/66866462/152325515-154bda81-0c0b-4d80-ba02-28c6074b7605.png)

Liegt das eventuell an den Farbeinstellungen. Dort gibt es keinen haken für die startseite.
![image](https://user-images.githubusercontent.com/66866462/152325924-8d93bdee-0f2d-4c83-8d0d-69df0b6dbbc4.png)

**Comment by ChristinaGu** [comment]
Es sind nur die Farben verfügbar, die gar keinen Haken haben und damit übergreifend gelten. Hast du vlt. die Einstellungen eingepasst und deswegen sind sie jetzt weg?

**Comment by laurahll** [comment]
Ja sicher, als es um die icons ging. dh ich müsste zB bei ocker und hellblau alle haken rausnehmen? nicht so schöne lösung weil die farbe bei der feuersozietät nichts zu suchen hat.

**Comment by ChristinaGu** [comment]
geht im Moment nicht anders und die Farben sehen ja ohnehin nur Redakteure

**Comment by ChristinaGu** [comment]
Für die schönere Lösung war kein Budget mehr da und das ist ein Feature dass nur für die VKB relevant ist. Daher nicht spannend für die restlichen Hubs, da sonst niemand Spaces nutzt.
