### ISSUE TITLE
Feature: Hinweise für neue Funktionen für Editoren

### ISSUE THREAD

**Issue by ChristinaGu** [wirDesign-communication-AG/wirHub-doc#24]
Als Administrator möchte ich Editoren auf neue Funktionen und Inhalte aufmerksam machen können. Eine News besteht aus Bild / Video oder Animation (Lottie JSON) und Text (MDE). 

Wurde eine neue News eingestellt, erscheint diese nach dem ersten Login nach Einstellen der News bei allen Editoren und Administratoren als Pop-Up. Dabei kann es mehrere News geben, die durchgeblättert werden können. Das Pop-Up kann geschlossen werden und später über dem Edit-Button auch wieder aufgerufen werden.

Später soll das Feature auch auf Nutzer mit Leserechten ausgeweitet werden. Ein Admin kann dann zwischen "News für Editoren" und "News für alle Nutzer" wählen.

- [ ] Neuer Navigationspunkt Einstellungen > Administration > News
- [ ] Backend für neue News anlegen 
- [ ] Frontend für News (siehe Designs)

**Abstract Links**
https://share.goabstract.com/25fbd63c-9c65-43d2-9623-cf12713467bd?mode=design&sha=4eab34cbca04c3e40f88d6241d6a8a742cda3839
https://share.goabstract.com/8c8a44d6-233f-4891-b677-20c805d8d0d5?mode=design&sha=45be393d2ecccbef93b7ffc646a177285ac2fd38

**Design**
![f13cafb0-1751-4312-a1b2-ea1b4e32cbdf](https://user-images.githubusercontent.com/8007132/115897800-19ff2f00-a45d-11eb-9d09-43fd8c2e8e69.png)
![4c6a1125-fbf5-4c94-9984-1b37c4796f77](https://user-images.githubusercontent.com/8007132/115897805-1bc8f280-a45d-11eb-8612-61cd54ce0300.png)
![25e86ea9-d4f2-4310-afd7-f3b3b2d7f207](https://user-images.githubusercontent.com/8007132/115897810-1d92b600-a45d-11eb-8da0-7b2f071af4d8.png)

**Comment by pmdevelopment** [comment]
Ist das "Design Required" label noch aktuell oder sind die Bilder das Design?

**Comment by ChristinaGu** [comment]
Was noch fehlt ist wie es im Backend genau funktioniert oder?
Dazu wollte ich aber vorher erstmal kurz mit dir und Esther sprechen bevor sie da was designed. Stelle uns einen Termin ein. Das Design für das Frontend ist fertig, siehe auch Abstract Link
