### ISSUE TITLE
Smartblock Anmerkung: Punkte auf dem Bild überlagern sich

### ISSUE THREAD

**Issue by nicolekalinowski** [wirDesign-communication-AG/wirHub-doc#244]
Die Punkte der Anmerkungen auf dem Bild, sind alle an der selben Position und überlagern sich dadurch. Eine Änderung der Positionen ist nicht möglich.
<img width="1363" alt="anmerkung-positionierung" src="https://user-images.githubusercontent.com/98943318/152743663-deb2abc7-0835-4f14-b11a-c2b693bc766e.png">

**Comment by laurahll** [comment]
Man kann sie nur im Bearbeiten Modus verschieben. Vielleicht wäre es hilfreich, wenn sie nebeneinander erscheinen.
![image](https://user-images.githubusercontent.com/66866462/152765893-3ec67620-e3a1-47f8-a1e1-d284c429a203.png)

**Comment by nicolekalinowski** [comment]
@laurahll danke für den Hinweis. Mir war unklar, dass/wie ich die Punkte verschieben kann - obwohl ich das eigentlich erwartet habe. Für mein Empfinden reicht es auch, wenn das bei der Beschreibung zum drag & drop ebenfalls beschrieben ist. Und/oder dass als Tooltip bei hover des Punktes im Bild zB "per drag and drop verschieben/positionieren" angezeigt wird.
