### ISSUE TITLE
SmartBlock Hinweis: Fehler 500 nach Speichern ohne Auswahl von "Art"

### ISSUE THREAD

**Issue by nicolekalinowski** [wirDesign-communication-AG/wirHub-doc#246]
- [ ] Standard als Default festlegen

Wenn ich einen Hinweis anlege und nicht explizit eine Darstellung unter "Art" wähle, gibt es beim Speichern einen Fehler 500. 

Ich vermute, das liegt daran, dass "Standard" nicht per Default gewählt ist. Sobald ist einen Wert setze, kann ich fehlerfrei speichern.

<img width="1649" alt="hinweis-art" src="https://user-images.githubusercontent.com/98943318/152750125-615f6cf0-2bda-4878-95f4-4a8a635c4ed5.png">

**Comment by karatektus** [comment]
Done.
