### ISSUE TITLE
SmartBlock Headline: HTML in Sprungmarkennavigation nicht berücksichtigen

### ISSUE THREAD

**Issue by ChristinaGu** [wirDesign-communication-AG/wirHub-doc#26]
HTML in Sprungmarkennavigation nicht berücksichtigen, sodass nur Text angezeigt wird 

![7819b2f1-27d2-4ddb-add3-813e6effb9bd](https://user-images.githubusercontent.com/8007132/115022215-6080e680-9ebd-11eb-81ba-b791d0386d33.jpg)

**Comment by pmdevelopment** [comment]
Wird der text innerhalb der HTML-blocks ebenfalls ignoriert oder angezeigt?

**Comment by ChristinaGu** [comment]
hm - schwierige Frage. Wenn man ein <strong> verwendet möchte man ja das es angezeigt wird. In diesem speziellen Fall macht es nicht viel Sinn. Aber ich denke dass das hier oben eher die Ausnahme ist. 

Deshalb bin ich für anzeigen.
