### ISSUE TITLE
SmartBlock Top News

### ISSUE THREAD

**Issue by ChristinaGu** [wirDesign-communication-AG/wirHub-doc#262]
Mit Hilfe eines neuen SmartBlocks soll es in Zukunft möglich sein die Top 3 News auf einer beliebigen Seite in Form eines Sliders platzieren zu können. 

**Design**
https://share.goabstract.com/cf6e282e-439f-48ce-a4c0-df4a0e46a0b0?collectionLayerId=f6a180a9-c6fc-4912-aaf9-a14f8ce491c2&mode=design

Achtung im Design gibt es einen kleinen Fehler. Auf dem Button steht "Jetzt ausprobieren" statt "Jetzt mehr erfahren". Der Text kann hier im Moment noch nicht geändert werden. Das soll erst mal so bleiben. Dort steht dann deshalb natürlich wie auf der News Übersichtseite auch "Jetzt mehr erfahren".

- [x] SmartBlock kann nur eingesetzt werden wenn News Feature aktiviert ist
- [x] News werden nur als Slider angezeigt, wenn es mehr als eine News gibt
- [x] Unter Bearbeiten > Zugriff sollten die Spracheinstellungen ausgeblendet werden. Der Smart-Block sollte immer auf allen Sprachen sichtbar sein

**Zugehöriges Redmine Ticket**
#7146

**Job**
K**-21136

**Comment by karatektus** [comment]
Funktioniert soweit. der letzte punkt fehlt noch. 
https://kws-staging.wirhub.de/default/style/category/various-stuff <- hier ganz unten ist er schon eingebunden.

**Comment by nicolekalinowski** [comment]
Hi @karatektus. Folgende Anmerkungen habe ich: 

- Der Button weicht vom Layout ab (orange, ohne Pfeil, Schrift weiß)
- Die Slidepfeile sind im Layout schwarz
- Das Badge weicht vom Layout ab (grau mit schwarzem Text)
- Das Datum ist im Layout nicht vorhanden
- Die Headline ist im Layout bold 
- Die Darstellung wenn nur eine News vorhanden ist, ist abweichend vom Layout. Im Layout ist hier zB die Positionierung des Badges anders. Ich habe hierfür mal alle außer deine News deaktiviert, aktivier sie dir bei Bedarf einfach wieder.
- Der letzte Punkt in der Checkliste oben bzgl. Spracheinstellungen ist noch offen.

Bitte vergleich das nochmal mit dem Design:
https://share.goabstract.com/cf6e282e-439f-48ce-a4c0-df4a0e46a0b0?collectionLayerId=f6a180a9-c6fc-4912-aaf9-a14f8ce491c2&mode=design

**Comment by karatektus** [comment]
Erledigt. 
Zu den offenen Punkten: 
Sliderpfeile und Badge sind Theme vermute ich und haben nix mit mir jetzt akut zu tun.
Das "Nur eine News" Thema habe ich garnicht gesehen. Das muss ich im Zweifel nachliefern

**Comment by karatektus** [comment]
button sollte auch theme sein ja. ist ein "btn-brand"

fixes sind raus. sollte soweit funktionieren.
