### ISSUE TITLE
Passwort zurücksetzen - Signatur anpassen

### ISSUE THREAD

**Issue by ChristinaGu** [wirDesign-communication-AG/wirHub-doc#263]
Wenn ein Nutzer sein PW zurück setzen möchte, erhält er aktuell folgende Mail 

---- 
Hallo Max Mustermann,

besuche bitte folgende Seite, um dein Passwort zurückzusetzen:

<link>

**Liebe Grüße,**

**dein wirHub Team**

----

Als Signatur sollte aber die Signatur verwendet werden die unter Einstellungen > E-Mails > Signatur eingestellt werden kann. 

Bitte anpassen

**Comment by pmdevelopment** [comment]
Nicht reproduzierbar.
