### ISSUE TITLE
SmartBlock SCORM: Umsetzung

### ISSUE THREAD

**Issue by pmdevelopment** [wirDesign-communication-AG/wirHub-doc#264]
- [x] Anlegen des SmartBlocks
- [x] Upload einer ZIP Datei
- [x] Ausgabe des SCORM Contents
- [x] Ersetzen der ZIP-Datei per Inline-Toolbar

Jobnummer: ***-22147
Budget: 24h

Redmine
#7150

**Comment by nicolekalinowski** [comment]
Umsetzung getestet auf https://kws-staging.wirhub.de/default/style/category/scorm-test - keine Fehler.

**Comment by nicolekalinowski** [comment]
Mir ist doch noch ein Fehler aufgefallen, der auf den ersten Blick nicht zu sehen war. In manchen Folien sind Grafiken eingebunden, die nicht angezeigt werden. 

Auf Seite 23 wird zB der Feuerlöscher angezeigt. Im wirHub ist an der Stelle nur ein leerer Kasten. Das kommt auf mehreren Seiten vor. @pmdevelopment  bitte prüf das nochmal
<img width="978" alt="image" src="https://user-images.githubusercontent.com/98943318/157834723-46b77965-5144-42d0-a6ac-c2addf4bb0a6.png">

<img width="669" alt="image" src="https://user-images.githubusercontent.com/98943318/157834868-d0fa00e1-ab0c-429c-b7e9-90ebea0e34e5.png">

**Comment by pmdevelopment** [comment]
Ursache sind fehlerhafte SVGs. Konnte ich durch eine Manipulation der Bilder von unserer Seite beheben.

**Comment by nicolekalinowski** [comment]
Getestet, fehlerfrei.
