### ISSUE TITLE
Verwaltung von E-Mail Templates

### ISSUE THREAD

**Issue by ChristinaGu** [wirDesign-communication-AG/wirHub-doc#265]
Neuer Tab unter Administration > Funktionen > E-Mails. 

Alle E-Mail Templates so wie alle bereits vorhandenen Einstellungsmöglichkeiten unter Administration > Einstellungen > E-Mails sind hier konfigurierbar. 

- [x] Einladungsmail
- [x] Passwort vergessen
- [x] Hinweis bei neuem Kommentar 
- [x] Kommentar Mention

**Comment by pmdevelopment** [comment]
Wichtig: die Templates finden sich unter Administration => Sprachen => Templates. Standardmäßig werden für deutsch und englisch schon Inhalte hinterlegt, das obligatorische Anlegen einer Invite-Mail bei neuen wirHubs entfällt. Allerdings müssen bei ALLEN bestands-wirHub die Texte der Invitation angepasst werden. Copy-Paste funktioniert nicht, da die Parameter  verändert sind.

**Comment by nicolekalinowski** [comment]
Testing ist erfolgt, die Bearbeitung der Templates ist möglich. 

@ChristinaGu  ich habe eine Verständnisfrage zu diesem Ticket: 
Möchtest du, dass die Absender und Signatur Einstellungen zusammen mit den Templates auf einer Seite sind?

Absender und Signatur sind momentan unter Administration > Einstellungen > E-Mails. 
Die Templates unter Administration => Sprachen => Templates

**Comment by nicolekalinowski** [comment]
ok dann passt das so und kann released werden.
