### ISSUE TITLE
Anmelden > Browser Hinweis > HTML Formatierung möglich

### ISSUE THREAD

**Issue by ChristinaGu** [wirDesign-communication-AG/wirHub-doc#267]
Hier
https://brandnet.kws.com/settings/design/login

soll beim Bearbeiten des Browser-Hinweises auch HTML wie z.B. ein `<br>` eingeben und erkannt werden können. 

**Job**
Retainer Mehraufwände Programmierung

**Budget** 
1h

**Zugehöriges Ticket**
7233

**Comment by nicolekalinowski** [comment]
@pmdevelopment ein `<br>` wird weiterhin als Text, nicht als HTML ausgegeben. 
<img width="849" alt="image" src="https://user-images.githubusercontent.com/98943318/157885713-95b20d91-6096-47ce-b65b-bd1ac9eb4a6e.png">

**Comment by pmdevelopment** [comment]
Auch hier die gleiche Thematik, solange das News Thema nicht durch ist wird das Update nicht online sein. Allerdings ist das auch eine Fehlannahme im Ticket mit dem <br>, mit dem Update werden Zeilenumbrüche einfach als solche dargestellt und der normale Textbearbeitungs-Editor steht zur Verfügung.

**Comment by nicolekalinowski** [comment]
Getestet, fehlerfrei.
