### ISSUE TITLE
News Feature: Feedbackschleife 1

### ISSUE THREAD

**Issue by ChristinaGu** [wirDesign-communication-AG/wirHub-doc#269]
- [x] In der News-Übersichtseite (/news) fehlt der Language Switch im Menü
- [x] Bei den internen Link ist es nicht möglich einen Link aus der 3. Navigationsebene auszuwählen (z.B. Corporate Design > Basiselemente > Logo) (komplette news verlinkung)
- [x] Formatierungen, die im MDE gesetzt werden, werden nicht richtig ausgegeben z.B. wird **Bold** `**Bold**` dargestellt

**Comment by karatektus** [comment]
Interner Link hat ein Update bekommen. ist noch nirgends live. das muss ich noch in diversen wirhub configs durchtesten.
Maximaler pain.

**Comment by nicolekalinowski** [comment]
Testing ist erfolgt, funktioniert.
