### ISSUE TITLE
SmartBlock Iconlist: Download funktioniert erst nach page refresh

### ISSUE THREAD

**Issue by ChristinaGu** [wirDesign-communication-AG/wirHub-doc#27]
Schritte zur Reproduzierung:

1. Neues Icon (SVG) hochladen
2. Icon auswählen
3. Verschiedene Formate anwählen und auf "Download" klicken

Download wirft Fehlermeldung und funktioniert erst nach manuellem page refresh
![Bildschirmfoto 2021-04-19 um 11 13 08](https://user-images.githubusercontent.com/8007132/115214947-4cc6c180-a103-11eb-9fa1-56691860ad71.png)

**Comment by pmdevelopment** [comment]
Der Bug war nicht reproduzierbar, allerdings habe ich ihn zum Anlass genommen das JavaScript in die Vanilla-Umsetzung zu übernehmen.
