### ISSUE TITLE
SmartBlock Animation: Meldung "Dies ist keine JSON Datei" bei zweitem Speichern

### ISSUE THREAD

**Issue by nicolekalinowski** [wirDesign-communication-AG/wirHub-doc#272]
Ich kann eine Animation mit JSON Datei anlegen und sie fehlerfrei angezeigt. Bearbeite ich das Element (zB de-/aktivieren einer Option) und speicher den Smartblock erneut, dann kommt die Meldung "Dies ist keine JSON Datei".

<img width="643" alt="sb-animation-json-warnung" src="https://user-images.githubusercontent.com/98943318/157724324-d492f670-9d08-4f6c-8136-8fb72ff695fd.png">

**Comment by ChristinaGu** [comment]
@karatektus könntest du dir das bitte anschauen. Ich glaube du hattest die Validierung damals eingebaut oder?

**Comment by karatektus** [comment]
done
