### ISSUE TITLE
SmartBlock UI Pattern: Meldung "schwerwiegender Fehler" nach Vorschau/Speichern

### ISSUE THREAD

**Issue by nicolekalinowski** [wirDesign-communication-AG/wirHub-doc#275]
Wenn ich im Bearbeitungsmodus auf "Vorschau aktualisieren" klicke, kommt die Meldung "Es ist ein schwerwiegender Fehler aufgetreten. Bitte lade die Seite erneut.". Das Speichern funktioniert und die Ausgabe des Patterns ebenfalls. Öffne ich den Bearbeitungsmodus erneut, kommt wieder dies Fehlermeldung. Ich kann die Inhalte aber normal bearbeiten.

<img width="1621" alt="sb-ui-pattern-fehlermeldung" src="https://user-images.githubusercontent.com/98943318/159152011-56304081-81b1-4586-bd2f-0c304459f755.png">

**Comment by pmdevelopment** [comment]
`src/StyleBundle/Controller/Element/PatternController.php:77` ist schuld, der Controller stammt aus dem Mittelalter und muss überarbeitet werden.
