### ISSUE TITLE
SmartBlock Do's und Don'ts: Beschreibung als Beschriftung nutzen

### ISSUE THREAD

**Issue by nicolekalinowski** [wirDesign-communication-AG/wirHub-doc#284]
Die Einträge der Do's und Dont's sind im Akkordeon. Als Label dafür wird momentan "Eintrag 1, Eintrag 2, .." gesetzt. Hier wäre es gut der Text aus dem Feld "Beschreibung" als Beschriftung der Accordion-Einträge genutzt wird.

**Comment by pmdevelopment** [comment]
Die einzige naheliegende Umsetzung war die Überführung des Moduls zum Inline-Editing und das habe ich entsprechend gemacht.
