### ISSUE TITLE
SmartBlock Ansprechperson: Optimierungen

### ISSUE THREAD

**Issue by ChristinaGu** [wirDesign-communication-AG/wirHub-doc#295]
- [x] Name, Position, Telefon und E-Mail Adresse nur anzeigen, wenn bei "Verknüpfter Benutzer" "Keine Verknüpfung" ausgewählt ist. Sobald eine Person aus der Benutzer DB gewählt wird, Felder ausblenden
- [x] Nur Name und Position required. Rest optional

**Comment by pmdevelopment** [comment]
Das war schon gemerged, aber falsch bezeichnet.
