### ISSUE TITLE
SmartBlock UI Pattern: Fehler 500

### ISSUE THREAD

**Issue by laurahll** [wirDesign-communication-AG/wirHub-doc#297]
Beim Bearbeiten des UI Pattern Moduls kommt folgender Fehler "Es ist ein schwerwiegender Fehler aufgetreten. Bitte lade die Seite erneut."
in der Konsole:
`POST https://www.markenportal-versicherungskammer.de/versicherungskammer-bayern/style/element/el_5eca9e1f3611e4a4e7/pattern/preview-create 500 (Internal Server Error)
`
Beispiel hier v2.3.15: Modul Buttons
https://www.markenportal-versicherungskammer.de/versicherungskammer-bayern/style/category/basics

**Comment by ChristinaGu** [comment]
Ist ein Duplikat von #275 bzw. #290 und bereits behoben. Nur noch nicht überall deployed
