### ISSUE TITLE
SmartBlock IconList: Dateiname bei Download einzelner Icons

### ISSUE THREAD

**Issue by skkii** [wirDesign-communication-AG/wirHub-doc#3]
Downloads of single assets as zip archives are not specifically awarded. For example, if a user downloads several single icons in a row, she/he would get a download file structure like icons-1.zip, icons-2.zip and so on depending on the operating system. A file name scheme like eg. brand-iconfilename.zip would be better at this point.

This also applies to fonts that are delivered as fonts.zip. A file name scheme like eg. brand-fonts.zip would be more unique and thus clearer for users to understand.

**Comment by ChristinaGu** [comment]
Ein Anfang wäre sich um die Iconliste  zu kümmern. Im Moment heißen alle Downloads wie beschrieben icon-list.zip. Lädt man mehrere Icons herunter hat man icon-list.zip, icon-list(1).zip usw. im Download-Ordner und kann die Icons nicht mehr zuordnen. 

Das zip sollte genauso wie das Icon heißen. Den Space-Namen würde ich nicht davor schreiben. Das müssen wir wenn dann mal als Option einbauen. Ich weiß das das nicht von jedem Kunden automatisiert gewünscht sein wird.
