### ISSUE TITLE
Space Overview: New Design

### ISSUE THREAD

**Issue by ChristinaGu** [wirDesign-communication-AG/wirHub-doc#30]
Das Design hierfür wurde mittlerweile freigegeben. Ich schlage vor, wir teilen die Seite in die Unterfeatures auf, die wir dafür benötigen und benutzen das hier als Sammelticket dafür. 

Zugehörige Untertickets: 
- [x] #114 
- [x] #115 
- [x] #121 
- [x] #122
- [x] #123
- [x] #125
- [x] #126
- [x] #127
- [x] #129
- [x] #148
- [x] #163 

Zusätzlich
- [x] #198 
- [x] #199
- [x] #197 

**Design**
https://share.goabstract.com/ce596bb6-0e5d-4d6c-906f-5a63395abf14?collectionLayerId=b2a34da3-a690-4f34-87a9-0051073ff58e&mode=design&sha=a6343f98b601c9898374b32487ab69721887679c

V**-21261 / 10

**Comment by pmdevelopment** [comment]
Anmkerkung zur Stage: wir haben kein Design für die Kombination "meistbesuchte Kapitel anzeigen" und "Nutzer hat noch keine Kapitel gesehen". Sollen wir hierbei dann auf die globalen Top 5 gehen mit einem anderen text?

**Comment by laurahll** [comment]
stimmt. wurde vergessen. Top 5 wäre eine gute Alternative. Kläre ich morgen vormittag

**Comment by laurahll** [comment]
Wir lassen das lieber mit den globalen Top 5. Würde den Nutzer zu sehr verwirren, wenn sich das ändert. Besonders weil die Headline über den Links nur einmal gelesen wird und dann prägen sie sich das falsch ein.
Hier die Ergänzung, was stattdessen dort stehen soll. 
https://share.goabstract.com/dff62c5c-de7f-4a7c-949c-c3ba0ee31e3b 
Icon: insert_chart_outlined
