### ISSUE TITLE
Template für Login innerhalb der Seite fehlerhaft

### ISSUE THREAD

**Issue by ChristinaGu** [wirDesign-communication-AG/wirHub-doc#306]
Siehe z.B. 
https://brandnet.kws.com/default/style/category/contacts

Erwartetes Ergebnis
Login Maske in Portlet, Sidebar bleibt bestehen

Bisheriges Ergebnis
Zerschossener Login Screen

**Comment by pmdevelopment** [comment]
Wie besprochen wird zur Vereinfachung weiter die Login-Seite verwendet, aber natürlich der Style gefixed. Dazu wird eine Meldung gezeigt:

    Der Zugriff auf diese Kategorie ist mit dem angemeldeten Benutzer nicht möglich. Bitte nutze ein Konto mit ausreichenden Berechtigungen.

Eine Integration in die Seite selbst wird erst relevant, wenn ein öffentlicher wirHub in Teilbereichen privat sein soll.
