### ISSUE TITLE
SmartBlock News: Probleme bei Rollen- und Rechte

### ISSUE THREAD

**Issue by ChristinaGu** [wirDesign-communication-AG/wirHub-doc#309]
Einige Nutzer scheinen die News nicht zu sehen. 

Zugehöriges Redmine Tickets: 
https://collaboration.wirdesign.de:8443/issues/7446

Gerne Rückfragen direkt dort stellen

**Comment by pmdevelopment** [comment]
Ursache ist die Verwendung der Rolle "ROLE_DESIGNER", die OAuth-Benutzer nicht haben. 

Lösung; Entfernung der Rolle "ROLE_DESIGNER" aus dem gesamten System.
