### ISSUE TITLE
Google Analytics: Event Integration

### ISSUE THREAD

**Issue by ChristinaGu** [wirDesign-communication-AG/wirHub-doc#312]
Siehe
#7478 (Redmine)

Notiz zum Aufwand, angepasst werden müssen:

- 4 SmartBlocks/Tools
- 3 Plugins
- 2 Unterseiten
- 2 Scripts

**Comment by pmdevelopment** [comment]
Folgendes Konzept geht per E-Mail an die Beteiligten:



## Anmerkungen vorweg

- "Tools > File transfer" ist ein Tracking des Buttons "Neue Datei hochladen" gewünscht. Der Button führt auf eine neue Unterseite (`/myhub/file-transfer/upload`), sollte somit vom regulären Tracking gedeckt sein. 
- "Variety Guide Creator" ist ein Tracking des Buttons "

## Seitenaufrufe

Hier würden wir wie im Beispiel angegeben das Event "brandnet_page_view" auslösen mit dem Titel der Kategorie als Kontext.

_=> Macht es Sinn das auszulösen, oder sollte man es nicht nutzen wenn es keine abweichenden Titel übergibt?_

## Downloads

### SmartBlock Attachment

Der Klick auf den SmartBlock löst den Download aus. Dabei wird folgendes Event getriggered:

    {
      event: 'brandnet_download',
      tracking: {
        context: 'Anhang', // Typ des Smartblocks
        title: 'Vertriebstechnik-Trainings', // Titel der Seite
        file: 'Trainingsbeschreibung_Rhetorik_DE.pdf' // Download-Name
      }
    }

### SmartBlock IconList

Wähle ich ein einzelnes Icon, kann ich es in verschiedenen Formaten herunterladen. Dabei wird folgendes Event getriggered:

    {
      event: 'brandnet_download',
      tracking: {
        context: 'Icons', // Typ des Smartblocks
        title: 'Icon-Bibliothek', // Titel der Seite
        file: 'Canister-Kanister.zip' // Download-Name
      }
    }

_Der Dateiname entspricht dem Archiv. Wollen wir hier statt dessen die ausgewählten Formate übergeben, bspw. `Canister-Kanister.svg|Canister-Kanister.eps`?_

Dazu kann ich eine Collection im Ganzen herunterladen. Dabei wird folgendes Event getriggered:

    {
      event: 'brandnet_download',
      tracking: {
        context: 'Icons', // Typ des Smartblocks
        title: 'Icon-Bibliothek', // Titel der Seite
        file: 'Tiere.zip' // Download-Name
      }
    }

_Sollte hier eine Unterscheidung getroffen werden, um die Collection als solche besser zu erkennen? Bspw. könnte man `title: 'Icons-Bibliothek: Collection'` verwenden, den Namen der Collection erhält man weiterhin aus `file`._


### SmartBlock Video

Wenn ich die Wiedergabe eines Videos starte ist das technisch gesehen kein Download, lässt sich darüber aber ideal einordnen. Daher wird folgendes Event getriggered:

    {
      event: 'brandnet_download',
      tracking: {
        context: 'Video', // Typ des Smartblocks
        title: 'Marketing-Trainings', // Titel der Seite
        file: 'Salesforce_Tutorial_Beginners_v2.mp4' // Datei-Name
      }
    }


### Plugin Media Creator

Generiere ich ein Bild über den Media Creator, kann ich das am Ende herunterladen. Dabei wird folgendes Event getriggered:

    {
      event: 'brandnet_download',
      tracking: {
        context: 'Media Creator', // Typ des Smartblocks
        title: 'Facebook', // Gewähltes Format
        file: 'feed_posting-text_only.jpg' // Download-Name
      }
    }

Über die Kombination aus `title`und `file` lässt sich das gewählte Medium vollständig aufschlüsseln.

### Plugin Teams Backgrounds

Generiere ich einen Microsoft Teams Hintergrund, kann ich das Bild im letzten Schritt herunterladen. Dabei wird folgendes Event getriggered:

    {
      event: 'brandnet_download',
      tracking: {
        context: 'Teams Backgrounds Creator', // Typ des Smartblocks
        title: 'Erbsen', // Gewähltes Bild
        file: 'kws_ms_teams_background_logo.jpg' // Download-Name
      }
    }

Über die Kombination aus `title`und `file` lässt sich das gewählte Medium vollständig aufschlüsseln.

## Interaktionen

### Plugin Media Creator

Wählt der Benutzer sein Medium, wird folgendes Event getriggered:

    {
      event: 'brandnet_button',
      tracking: {
        context: 'Media Creator', // Typ des Smartblocks
        text: 'Instagram' // Medium
      }
    }

Wählt er dann sein Format, wird folgendes Event getriggered:

    {
      event: 'brandnet_button',
      tracking: {
        context: 'Media Creator', // Typ des Smartblocks
        text: 'Instagram: Product Posting' // Medium: Format
      }
    }

## Plugin Variety Guide Creator

Innerhalb der Verwaltung einer Seite wird diese Über den Button "Veröffentlichen" finalisiert und dabei folgendes Event getriggered:

    {
      event: 'brandnet_button',
      tracking: {
        context: 'Variety Guide Creator', // Plugin Name
        text: 'Veröffentlichen' // Name des Buttons
      }
    }


### myHub QR-Code Generator

Um einen neuen QR-Code anzulegen wird über den Button "Neuen QR-Code erstellen" ein Dialog geöffnet und gleichzeitig folgendes Event getriggered:

    {
      event: 'brandnet_button',
      tracking: {
        context: 'QR-Code Generator', // Titel der Seite
        text: 'Neuen QR-Code erstellen' // Name des Buttons
      }
    }

## Suchen

Beim Auslösen einer Suche wird folgendes Event getriggered:

    {
      event: 'brandnet_search',
      tracking: {
        context: 'global', // Kontext
        text: 'Icons' // Suchbegriff
      }
    }

Unterschieden wird in folgende Kontexte:

| Context         | Beschreibung                            |
|-----------------|-----------------------------------------|
| global          | Erweiterte Suche                        |
| quick           | Schnellsuche                            |
| Activity Finder | Titel der Seite (SmartTool Inspiration) |
| Inspiration     | Titel der Seite (SmartTool Inspiration) |
| Icon-Bibliothek | Titel der Seite (SmartBlock Icons)      |

_Man könnte überlegen, ob man hier als Kontext neben `global` und `quick` den Typ des SmartBlocks einsetzt und den Titel der Seite als optionalen zusätzlichen Parameter integriert._

## Externe Verlinkung

Verschiedene Stellen verlinken auf externe Ziele (`target="_blank"), primär "Trainings". Klickt der Benutzer einen solchen Link, wird folgendes Event getriggered:

    {
      event: 'brandnet_link',
      tracking: {
        context: 'Marketing-Trainings', // Titel der Seite
        type: 'external', // Art
        target: 'https://trainings.kws.com/Brand_in_sales_EN/index_EN.php', // URL
        text: 'Brand in Sales DE' // Link-Text
      }
    }
