### ISSUE TITLE
SmartBlock IconList: Fehlerhafter Download

### ISSUE THREAD

**Issue by laurahll** [wirDesign-communication-AG/wirHub-doc#323]
Markenportal [v2.3.20]
Der Download der Icons als AI oder EPS funktioniert nicht richtig. Es wird eine Zip heruntergeladen, aber darin liegt nur eine Log Datei mit dem Inhalt:

Warning: Option --without-gui= is deprecated

** (process:667398): WARNING **: 17:06:33.278: Unable to create profile directory (Permission denied) (13)
Unable to init server: Could not connect: Connection refused
Unknown option -E

**Comment by pmdevelopment** [comment]
@laurahll das ist ein Problem mit dem spezifischen Server, um Wochen wirHub handelt es sich genau?

**Comment by laurahll** [comment]
Ums versicherungskammer markenportal 
https://www.markenportal-versicherungskammer.de/

**Comment by pmdevelopment** [comment]
Todos:
- Erkennung der Inkscape version
- Weiche zwischen 1.0 und älter. Ab 1.0 entfällt `--without-gui` und `-E` wird zu `--export-filename`
