### ISSUE TITLE
SmartBlocks: Einstellungen für Zugriff überarbeiten

### ISSUE THREAD

**Issue by ChristinaGu** [wirDesign-communication-AG/wirHub-doc#329]
Langfristig sollen alle Funktionen, die sich aktuell in der Toolbar hinter dem Edit-Icon befinden in das Inline-Editing bzw. in den Quick-Edit wandern. 

Die Zugriff-Einstellung bilden die Ausnahme und wandern in die Toolbar
![image](https://user-images.githubusercontent.com/8007132/181574207-54abf54c-efa8-45e2-adfe-f474ae3b5003.png)

Bei Klick auf das Icon öffnet sich folgendes Dropdown
![image](https://user-images.githubusercontent.com/8007132/181574421-1425fd0c-112c-4781-b5e8-2bf61af59e39.png)

Hierüber kann eingestellt werden in welcher Sprache der SmartBlock gesehen werden kann und ob der SmartBlock von Benutzern gesehen werden kann. Ist dieser Toggle aus, kann der SmartBlock nur von Editoren und Administratoren gesehen werden. Befindet sich ein Editor oder ein Administrator im View-Mode sollten diese SmartBlocks mit eine transparenten grauen Fläche und dem durchgestrichenen Augen Icon überlagert werden, sodass sie auf einen Blick sehen, welche Inhalte für Benutzer noch ausgeblendet sind.

![image](https://user-images.githubusercontent.com/8007132/181575232-85061c90-1d01-4d01-9b00-7d6294aeaf0c.png)

Design Specs: https://www.figma.com/file/4lvLk6rYqvKWJgf5hcjIsH/wirHub-Components-%26-Prototype?node-id=596%3A17358

**Comment by pmdevelopment** [comment]
![Screenshot 2022-09-19 105538](https://user-images.githubusercontent.com/4947485/190982816-a5f1695a-c221-4c87-9b02-439aea10c497.png)

Der SmartBlock "Note" hat eine zusätzliche Zugriffs-Option, wie stellen wir die dar?

**Comment by ChristinaGu** [comment]
Lass es und entfernen und hier genau so wie bei den anderen SmartBlocks handhaben. Also es gibt nur die Optionen "Sichtbar" und "Nicht sichtbar". Damit entfällt ja nur die Option sich selbst Notizen zu machen - was nach Rückfrage bei den Redakteuren ohnehin nicht genutzt wird.
