### ISSUE TITLE
SmartBlock Icons: Gelöschte Icons werden in Suche angezeigt

### ISSUE THREAD

**Issue by ChristinaGu** [wirDesign-communication-AG/wirHub-doc#331]
Sucht man im KWS BrandNet nach "Sorten-Berater" in der erweiterten Suche, erhält man ein Suchergebnis für "Corporate Design > Basiselemente > Icons(Icons)". 

Weder das Icon noch die Icon-Bibliothek existieren allerdings auf dieser Seite. 

Bitte prüfen
<img width="1176" alt="MicrosoftTeams-image (1)" src="https://user-images.githubusercontent.com/8007132/183405057-21ea547d-c0a9-46fe-9766-4c6f7bffbf3a.png">
.

**Comment by ChristinaGu** [comment]
find_stale_icons hat übrigens nicht geholfen

**Comment by pmdevelopment** [comment]
Ursache: Es war eine Icon-Liste in einem Accordion und das Accordion war gelöscht worden.

**Comment by pmdevelopment** [comment]
Side-Note: Enthält das Suchergebnis Icons, dann passt die Anzahl an Suchergebnissen nicht, wodurch fälschlich ein "Mehr"-Button gezeigt wird. Das Problem wird ebenfalls mit diesem Issue gelöst.

**Comment by pmdevelopment** [comment]
Der Rückwirkende Fix hat den Fall hier nicht abgedeckt, da hier das Accordion nie gelöscht wurde sondern nur das Item.
