### ISSUE TITLE
Link zu Nutzungsbedigungen wird auf Loginseite angezeigt auch wenn diese nicht gepflegt ist

### ISSUE THREAD

**Issue by ChristinaGu** [wirDesign-communication-AG/wirHub-doc#34]
Siehe z.B. hub.medios.ag

**Comment by pmdevelopment** [comment]
{%- if config_privacy -%}
        <a href="{{ config_tos }}" target="_blank">{{ 'config_template_tos'|trans }}</a>
    {%- endif %}

config_privacy muss config_tos prüfen in app_no_login.html.twig
