### ISSUE TITLE
SmartBlock Akkordeon: Print Funktion optimieren

### ISSUE THREAD

**Issue by ChristinaGu** [wirDesign-communication-AG/wirHub-doc#340]
print.css dahingehend erweitern, dass im PDF alle Akkordeons aufgeklappt mit vollem Inhalt angezeigt werden, sobald man eine Seite Drucken oder als PDF speichern möchte

BVR-21046I / 5h

**Comment by pmdevelopment** [comment]
Bei mir sind sie alle offen: 

[issue-340.pdf](https://github.com/wirDesign-communication-AG/wirHub-doc/files/9484525/issue-340.pdf)

**Comment by ChristinaGu** [comment]
huch - bei mir sieht das ganz anders aus

Chrome unter iOS
Version 104.0.5112.101 (Offizieller Build) (x86_64)
[Testing _ KWS BrandNet - Test System.pdf](https://github.com/wirDesign-communication-AG/wirHub-doc/files/9491404/Testing._.KWS.BrandNet.-.Test.System.pdf)
[Testing _ KWS BrandNet - Test System-aufgeklappt.pdf](https://github.com/wirDesign-communication-AG/wirHub-doc/files/9491405/Testing._.KWS.BrandNet.-.Test.System-aufgeklappt.pdf)
