### ISSUE TITLE
SmartBlock IconList: Löschen nicht möglich, wenn Icon-Attribut gesetzt ist

### ISSUE THREAD

**Issue by ChristinaGu** [wirDesign-communication-AG/wirHub-doc#354]
Ein Icon, das einer Kategorie oder einer Sammlung zugeordnet ist, kann nicht gelöscht werden. Es erscheint eine Fehlermeldung. 

Erwartetes Verhalten: Icon wird gelöscht und aus Sammlung bzw. Kategorie entfernt

**Error Log**
`[2022-10-10 09:51:29] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\ForeignKeyConstraintViolationException: "An exception occurred while executing a query: SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`wirhub`.`style_element_icon_attribute`, CONSTRAINT `FK_565CB1AB54B9D732` FOREIGN KEY (`icon_id`) REFERENCES `style_element_icon` (`id`))" at /var/www/wirHub/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php line 56 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ForeignKeyConstraintViolationException(code: 1451): An exception occurred while executing a query: SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`wirhub`.`style_element_icon_attribute`, CONSTRAINT `FK_565CB1AB54B9D732` FOREIGN KEY (`icon_id`) REFERENCES `style_element_icon` (`id`)) at /var/www/wirHub/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php:56, Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1451): SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`wirhub`.`style_element_icon_attribute`, CONSTRAINT `FK_565CB1AB54B9D732` FOREIGN KEY (`icon_id`) REFERENCES `style_element_icon` (`id`)) at /var/www/wirHub/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:28, PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`wirhub`.`style_element_icon_attribute`, CONSTRAINT `FK_565CB1AB54B9D732` FOREIGN KEY (`icon_id`) REFERENCES `style_element_icon` (`id`)) at /var/www/wirHub/vendor/doctrine/dbal/src/Driver/PDO/Statement.php:134)"} []`

**Comment by pmdevelopment** [comment]
Im gleichen Zug wird eine fehlerhafte Darstellung im Edit-Dialog behoben.
