### ISSUE TITLE
Feature: Analytics

### ISSUE THREAD

**Issue by ChristinaGu** [wirDesign-communication-AG/wirHub-doc#36]
Als Administrator möchte ich auf einem Dashboard einsehen können welche Seiten wie oft besucht und welche Downloads wie oft heruntergeladen wurden. 
- [x] Grobes Design für Frontend
- [x] Genaue Spezifikation (z.B. Daten splitten in "Öffentlicher Zugriff", "Zugriff per Token" und "Zugriff als Benutzer")

**Design**
https://www.figma.com/file/4lvLk6rYqvKWJgf5hcjIsH/wirHub-Components-%26-Prototype?node-id=595%3A13987

**Comment by pmdevelopment** [comment]
Eine Erwähnung in der Datenschutzerklärung ist nicht nötig, da wir in der Statistik keine personenbezogenen Daten speichern.

**Comment by ChristinaGu** [comment]
Schließe das Ticket und lege für weitere Bugs und Enhancements Folgetickets an
