### ISSUE TITLE
Toolbar: Diverse Optimierungen Part 1

### ISSUE THREAD

**Issue by ChristinaGu** [wirDesign-communication-AG/wirHub-doc#362]
- [x] Hochgesetzte Toolbar
- [x] Gestrichelte Border anstelle von box-shadow
- [x] SmartBlock Spalten: Toolbar und Inline-Editing hinter Gear-Icon
- [x] SmartBlock Spalten: Visibilty Optionen für Child-Elemente entfernen > erben Einstellungen von SB Column
- [x] ~~Bitte beachten das Icons in Toolbar kleiner geworden sind und Toolbar damit insgesamt etwas kleiner~~

**Design**
https://www.figma.com/file/4lvLk6rYqvKWJgf5hcjIsH/wirHub-Components-%26-Prototype?node-id=981%3A15777

**Comment by pmdevelopment** [comment]
Letzter Punkt vorerst gestrichen, kann für Part 2 diskutiert werden.
