### ISSUE TITLE
Variety Guide Creator: Erweiterung

### ISSUE THREAD

**Issue by ChristinaGu** [wirDesign-communication-AG/wirHub-doc#369]
- [ ] Subline unter dem Sortennamen integrieren (kommt aus PIM)
- [ ] Nutzungsicons und Texticons integrieren. Diese sollen unterhalb der Variety Characteristics stehen und sollen begrenzt sein auf max. 4 Stück. Die Icons sind auch im PIM hinterlegt und sollten auch automatisch rübergezogen werden.
- [ ] Die Sortenseite in unserem Guide soll dann ähnlich wie die Sortenbeschreibung auf unserer Website aussehen (Beispiel: https://www.kws.com/de/de/produkte/mais/sortenuebersicht/kws-inteligens/)
- [ ] Traits&Feautres ergänzen: BEST4N!, InsectPROTECT

Im angehängten Screenshot siehst Du links eine Seite aus unserem Guide und rechts die Sorte auf der Website. Rechts ist in Gelb nochmal markiert, welche Informationen wir wo ergänzen wollen.
![Erweiterung_Variety-Guide-Creator](https://user-images.githubusercontent.com/8007132/197980629-e69b0cdc-7c4e-4973-aadb-a648e624df88.png)

**Redmine**
#7818

*Jobnummer*
K**-22194

**Comment by karatektus** [comment]
Soweit erledigt. Für folgende usage icons konnte ich keine Zuordnung im PIM finden: 

Chips, FrenchFries, Sugar, TablePotatoes 

bitte zukünftig bei sowas bestenfalls das attribut unter dem es im pim läuft mitliefern.

**Comment by ChristinaGu** [comment]
Feedback von Kundin

_vielen Dank für die Anpassungen. Bitte noch folgende Änderungen vornehmen:

- Abstand zwischen den Nutzungsicons etwas vergrößern
- größere Schriftgröße der Stichpunkte, aber bitte nicht so groß wie die Subline/Slogan
- Bitte noch folgende Traits hinzufügen: Plus4GRAIN, ClimaCONTROL3, Seed2FEED, EnergyBoost by Seed2FEED
- Und noch eine Anmerkung. Im Testsystem gibt es ein paar Bugs mit der Anzeige von Buttons und Icons (siehe Screenshot), icons werden z.B. als Klartext angezeigt. Ich vermute das liegt am Testsystem und nicht an der Erweiterung des Creators?_

Das mit den Icons liegt daran das wir von Material Icons zu Material Symbols gewechselt sind. Bitte tausch dich mit Sven dazu aus
![Uploading Screenshot 2022-11-10 125118.png…]()

**Comment by karatektus** [comment]
Zu den Traits: Die sind dann genauso wie die Best4N! und INsectProtect Traits nur manuell auswählbar. Wenn die anhang vomPIM vorausgewählt werden sollen brauch ich da mehr infos.

**Comment by karatektus** [comment]
Material Symbols löst Sven unabhängig vom Variety Guide
