### ISSUE TITLE
Shortcuts

### ISSUE THREAD

**Issue by ChristinaGu** [wirDesign-communication-AG/wirHub-doc#372]
Wir führen Shortcuts ein und starten mit "command + E" bzw. "alt + E", um in den Edit-Mode zu wechseln.

- [x] Shortcuts werden dokumentiert via Hilfe-Icon im Footer (siehe Bug-Icon). 
- [x] Icon nur sichtbar für Editoren und Administratoren
- [x] Klick öffnet Dialog mit Shortcut-Auflistung

**Comment by pmdevelopment** [comment]
Folgende Problematik: "STRG+E" bzw. "ALT+E" sind von Chrome reservierte Shortcuts, daher würde ich nun mit "SHIFT+E" arbeiten.
