### ISSUE TITLE
Tabelle: Zeile löschen nicht möglich

### ISSUE THREAD

**Issue by ChristinaGu** [wirDesign-communication-AG/wirHub-doc#39]
Im Moment nur unter wirhub.wirdesign.de kaputt. Scheint also mit dem Quick-Edit zusammen zu hängen, siehe z.B. 
https://wirhub.wirdesign.de/default/style/category/zugange

Error.Log
`[2021-05-20 17:03:42] request.CRITICAL: Uncaught PHP Exception TypeError: "Return value of StyleBundle\Component\Model\ElementEntityModel::getAttributes() must be of the type array, null returned" at /var/www/wdc-styleguide/src/StyleBundle/Component/Model/ElementEntityModel.php line 104 {"exception":"[object] (TypeError(code: 0): Return value of StyleBundle\\Component\\Model\\ElementEntityModel::getAttributes() must be of the type array, null returned at /var/www/wdc-styleguide/src/StyleBundle/Component/Model/ElementEntityModel.php:104)"} []
[2021-05-20 17:03:42] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []`

**Comment by pmdevelopment** [comment]
Wird unter #22 behandelt
