### ISSUE TITLE
News: Pop-up bei Log-in

### ISSUE THREAD

**Issue by ChristinaGu** [wirDesign-communication-AG/wirHub-doc#390]
- [x] Anpassung des Dropdown Designs an den neusten Stand, das Design wird in dem Punkt ignoriert
- [x] Neues Design innerhalb des Dropdowns
- [x] Hervorhebung neuer News per Backdrop
- [x] Individuelle Überschrift (multilingual)
- [x] Button um News als gesehen zu markieren

Design: https://www.figma.com/file/naD4NLAVTXPw3i3fqxfWI1/Navigation-und-Startseite?node-id=310%3A1059&t=qDCRW1Drzfh9mRML-4

02h Design / 06h Dev

Klären: Gibt es nur die aktuell gestaltete Version oder darüber hinaus auch noch eine Version für besonders wichtige News als "echtes Pop-up" mit Bild/Video/Animation und Text

**Comment by pmdevelopment** [comment]
Ist das Design finalisiert?

**Comment by ChristinaGu** [comment]
Design liegt hier ab https://www.figma.com/file/naD4NLAVTXPw3i3fqxfWI1/Navigation-und-Startseite?node-id=310%3A1059&t=qDCRW1Drzfh9mRML-4

**Comment by pmdevelopment** [comment]
Anmerkung: Automatisch für alle News, sofern ungesehene vorhanden.
