### ISSUE TITLE
Feature: Seite hinzufügen

### ISSUE THREAD

**Issue by ChristinaGu** [wirDesign-communication-AG/wirHub-doc#4]
In #373 hatte ich leider einen kleinen Denkfehler. Und zwar darf es den gleichen Seitentitel nur in der der gleichen Navigationsebene nicht doppelt geben, in verschiedenen Ebenen allerdings schon. 

Zum Beispiel kann und darf die Seite mit dem Titel "Basics" unter zwei verschiedenen Unterkategorien existieren.

Corporate Design > Basics 

und 

Employer Branding > Basics 

Nicht zulässig ist nur dass der gleiche Seitentitel innerhalb der gleichen Ebene doppelt existiert.

**Comment by ChristinaGu** [comment]
Hast du Lokal außerdem mit Spaces getestet? In zwei verschiedenen Spaces kann der Seitentitel "Corporate Design" ja auch doppelt vorkommen.

**Comment by ChristinaGu** [comment]
Ok habs getestet. Es geht.

**Comment by karatektus** [comment]
An Spaces hab ich natürlich selber gedacht!
