### ISSUE TITLE
Seitenverwaltung: Oberkategorien inkl. Unterseiten in Spaces verschieben

### ISSUE THREAD

**Issue by ChristinaGu** [wirDesign-communication-AG/wirHub-doc#407]

**Comment by ChristinaGu** [comment]
@pmdevelopment: leider buggy. Versucht man z.B. irgend einen Punkt unter Create > Tools > ... in kws-upgrade zu bearbeiten, lädt er unendlich.

**Comment by pmdevelopment** [comment]
Der Bug wurde für #356 schon gelöst, ich bringe kws-upgrade im Laufe des Vormittags in die WIP-Branch.
