### ISSUE TITLE
Benutzerverwaltung: Search Query wird nicht zurück gesetzt

### ISSUE THREAD

**Issue by ChristinaGu** [wirDesign-communication-AG/wirHub-doc#412]
Es gibt schon seit einiger Zeit einen nervigen Bug: sobald ich in der Benutzerverwaltung nach etwas bzw. jemanden Suche und dann z.B. die Einstellungen bei der betroffenen Person ändere und zurück in die Benutzerverwaltung gehe und eine weitere Aktion ausführe, ist immer noch die alte Suche aktiv. 

Reproduzieren
https://kws-staging.wirhub.de/admin/user

> nach Christina suchen
> meine Einstellungen öffnen und einfach speichern
> einen anderen Nutzer auswählen
> speichern
> Filter "Christina" immer noch aktiv

**Comment by pmdevelopment** [comment]
Das ist ein Feature

**Comment by ChristinaGu** [comment]
Ja aber selbst wenn ich den Filter über das "x" weg klicke, verhält es sich immer noch so. Spätestens dann würde ich erwarten, dass er die Suche zurück setzt
