### ISSUE TITLE
Individuelle Verlinkung im Benutzermenü

### ISSUE THREAD

**Issue by pmdevelopment** [wirDesign-communication-AG/wirHub-doc#421]
Wurde gewünscht, entsprechende Klärung erforderlich.

Design, siehe https://www.figma.com/file/4lvLk6rYqvKWJgf5hcjIsH/wirHub-Components-%26-Prototype?node-id=1972%3A26707&t=NcFn1bFIAMyUCVH1-1

**Comment by ChristinaGu** [comment]
Mit Laureen klären, was hier genau gewünscht war

**Comment by ChristinaGu** [comment]
Anforderungen Design
- [ ] Wie und wo stelle ich als Admin, welche Seiten dort verlinkt werden?
