### ISSUE TITLE
Bookmarks beim Löschen von Seiten erhalten

### ISSUE THREAD

**Issue by pmdevelopment** [wirDesign-communication-AG/wirHub-doc#422]
Wird eine Seite gelöscht, müssen bestehende Bookmarks verarbeitet werden. Idee:

- Löschen öffnet einen Dialog, sofern Bookmarks bestehen
- Redakteur entscheidet "Bookmarks löschen", "Bookmarks auf neue Kategorie leiten" und "Ignorieren"

**Comment by ChristinaGu** [comment]
Für erste Ideen bräuchten wir mehr Budget. 

Alternativer Vorschlag: Umleitung auf eine eigens designte Seite "Diese Seite zu dem Bookmark existiert nicht mehr ...". Button <Bookmark entfernen>

**Comment by ChristinaGu** [comment]
Was passiert eigentlich wenn nur die Headline der Seite an der das Bookmark gesetzt wurde gelöscht wird?

**Comment by pmdevelopment** [comment]
Die Headline wird nur für den Titel beim Speichern genutzt, die Verlinkung geht immer auf die Seite und behält ihren Namen unabhängig von der Headline.
