### ISSUE TITLE
Fehlerhaftes Verhalten durch Toolbar/Quick Edit

### ISSUE THREAD

**Issue by pmdevelopment** [wirDesign-communication-AG/wirHub-doc#43]
- [x] Der "Hover" Rahmen erscheint auch, wenn man Bearbeiten wieder deaktiviert (Nur Dashboard!).
- [x] Checkbox im Dark Mode nicht lesbar

**Comment by ChristinaGu** [comment]
"Checkbox im darkmode nicht lesbar" > das ist doch immer noch so?! Oder ist das auf brandnet.kws.com noch nicht released?

**Comment by pmdevelopment** [comment]
Nicht deployed. Gir checkout v2.3 && symfony-update && php bin/console app:theme:refresh
