### ISSUE TITLE
Erweiterte Suche: um Dateien erweitern

### ISSUE THREAD

**Issue by ChristinaGu** [wirDesign-communication-AG/wirHub-doc#440]
Design mit Kunde abgestimmt und freigegeben. 

Siehe: https://www.figma.com/file/4lvLk6rYqvKWJgf5hcjIsH/wirHub-Components-%26-Prototype?node-id=1870%3A25760&t=NcFn1bFIAMyUCVH1-4

**Comment by pmdevelopment** [comment]
![Screenshot 2023-02-17 112556](https://user-images.githubusercontent.com/4947485/219619218-cf2fb776-57cd-4fc6-b60d-096b96b24de7.png)

Kleine Anmerkung noch: die einzige Möglichkeit die Schnellsuche zu schließen ist wieder oben aufs Such-Icon zu drücken, das ist imho nicht intuitiv
