### ISSUE TITLE
SmartBlock UI-Pattern: Hinterlegte Schriftarten können nicht bearbeitet werden

### ISSUE THREAD

**Issue by wirDesign** [wirDesign-communication-AG/wirHub-doc#45]
Der Bearbeiten-Knopf funktioniert nicht.

Ich kann die eigenen Schriftarten nicht bearbeiten. Das Pop-up öffnet sich nicht.

**Comment by pmdevelopment** [comment]
Das Problem ist bestätigt und wird für den Release am 21.6. gelöst. Auf welchem wirHub wird es konkret benötigt, damit das Update dort priorisiert deployed wird?

**Comment by ChristinaGu** [comment]
SMP ist der Hub
