### ISSUE TITLE
SmartBlock Bühne: Styles optimieren

### ISSUE THREAD

**Issue by ChristinaGu** [wirDesign-communication-AG/wirHub-doc#459]
Siehe zB Fehlverhalten hier
https://kws-upgrade.wirhub.de/learn/style/category/why-employer-branding

Bitte wie besprochen Bild in der Hintergrund und Aspect Ratio immer auf 16:9

**Comment by pmdevelopment** [comment]
Ursache war dieser custom style:

    .element--stage .stage {
        justify-content: end;
        height: 65vh !important;
        overflow: hidden;
        position: relative;
        .stage-video-background{
            position: absolute !important;
            height: 100%;
            width: 100%;
        }
    }
