### ISSUE TITLE
SmartBlock IconList: Pagination funktioniert nicht ohne Suche

### ISSUE THREAD

**Issue by nhinken** [wirDesign-communication-AG/wirHub-doc#470]
Die Icon Library vom PowerCo Hub funktioniert nicht richtig (https://hallo.wirhub.de/powerco/style/). Wenn man auf die weiteren Seiten klickt unten in der Navi (entweder über die Pfeile oder die Zahlen), kommt ein Ladezustand aber dann passiert nichts weiter. Die Funktion "Show all Icons of this Category" funktioniert aber.
![Bildschirmfoto 2023-02-06 um 12 50 10](https://user-images.githubusercontent.com/124579915/216964617-e1571298-48c9-485e-b63d-2c5be53f2ef4.png)
![Bildschirmfoto 2023-02-06 um 12 53 04](https://user-images.githubusercontent.com/124579915/216964776-2225a039-c79b-4ac4-b93a-fe3ebb0d8987.png)
@pmdevelopment @ChristinaGu

**Comment by ChristinaGu** [comment]
hab den Hub mal auf die neuste Version gebracht (-beta14). Fehler besteht immer noch. Kann bei KWS allerdings nicht reproduzieren. Evtl. weil keine Kategorien oder weil auf Dashboard eingesetzt.

JS Fehler
Uncaught TypeError: Cannot read properties of null (reading 'value')
    at default.manageSlide (icon_list.js:1:5280)
    at HTMLLIElement.<anonymous> (icon_list.js:1:2011)
manageSlide @ icon_list.js:1
(anonym) @ icon_list.js:1
