### ISSUE TITLE
SmartBlock Attachement: Datei löschen optimieren

### ISSUE THREAD

**Issue by ChristinaGu** [wirDesign-communication-AG/wirHub-doc#5]
Wenn ich als Editor eine Datei lösche, die nur auf dieser Seite existiert und kein weiteres Mal verwendet wird, sollte die Datei direkt ohne zusätzliches Modal und zusätzliche Bestätigung über den Radio-Button gelöscht werden. Die Bestätigung nach erfolgreichem Löschvorgang mittels Snackbar bleibt natürlich bestehen. 

Ist die Datei allerdings auch auf anderen Seiten als Attachement hinterlegt, sollte das Modal weiterhin erscheinen.  ~~Unter dem zweiten Radio-Button sollen außerdem die Seiten aufgeführt werden auf denen die Datei als Attachement hinterlegt ist. Dabei bitte nicht nur den Seitentitel sondern den kompletten Pfad, z.B. Corporate Design > Basics > Logo~~

**Comment by pmdevelopment** [comment]
Aufgrund einer Überschneidung mit #84 übernehme ich das Ticket.
