### ISSUE TITLE
Gruppen-Berechtigungen: Vorschau funktioniert nicht

### ISSUE THREAD

**Issue by ChristinaGu** [wirDesign-communication-AG/wirHub-doc#528]
Konkrete Todos:

- [x] Ansprechpartner-Seite statt 404 für "Startseite ausblenden"
- [x] Gruppen-Vorschau fixen

Ursprüngliche Diskussion:

Bei Wechsel zu Freelancer in kws-staging
- [x] erhält man einen 404 für jedes der drei Space Dashboards
- [x] sieht man Space-Overview mit allen Spaces (auch die, bei denen man keine Berechtigung hat) Evtl. Spaces um Gruppen erweitern 

Bei Wechsel zu Freelancer bei civey-staging
- [x] Funktioniert nicht. Es sollte nur die Seite "Test" sichtbar sein. Der Zugriff ist allerdings noch auf alle Seiten möglich ~~

**Comment by pmdevelopment** [comment]
a) 404 Bei Dashboards:

![image](https://user-images.githubusercontent.com/4947485/228446997-e2d95cd8-ae12-49cc-bde6-0cd0594e0d86.png)

Dashboards waren für die Gruppe Freelancer deaktiviert. Deaktiviere ich die Einstellung funktioniert alles. 

b) Es gibt keine Einschränkung auf Spaces, ergo werden alle Spaces gezeigt, das ist korrekt so

c) Zugriff auf alle Seiten ist nur im Preview möglich, ein realer Nutzer der Gruppe ist da eingeschränkt.

Meine Empfehlung wäre erstmal das Gruppen-Feature in Summe zu hinterfragen, bevor man hier anfängt Dinge zu ändern.

**Comment by ChristinaGu** [comment]
Aber dann sollte eigentlich kein 404 angezeigt werden, sondern das Dashboard mit Hinweis auf die eingeschränkten Berechtigungen und dem Verweis auf eine Kontaktperson. Das hatte auch schon mal so funktioniert

![Bildschirm­foto 2023-03-29 um 09 34 40](https://user-images.githubusercontent.com/8007132/228460244-9dbc5293-c22e-4cbe-85e4-119c1aa37e46.png)
