### ISSUE TITLE
SmartBlock Accordion: Anlegen von neuem SmartBlock nicht an richtiger Stelle

### ISSUE THREAD

**Issue by ChristinaGu** [wirDesign-communication-AG/wirHub-doc#54]
Fügt man innerhalb eines Akkordeon-Items einen neuen SmartBlock oberhalb oder unterhalb eines anderen hinzu, wird es nicht an der erwarteten Stelle platziert, sondern an irgendeiner Stelle innerhalb des Akkordeon-Items.

**Comment by pmdevelopment** [comment]
@karatektus ist noch Beschäftigt? Das ist ein Fall von "parallele Umsetzung des Testings".

**Comment by pmdevelopment** [comment]
@ChristinaGu nicht reproduzierbar, ich rbauche Details wo das stattfindet.
