### ISSUE TITLE
SmartBlock Annotation: Texte können nicht mehr bearbeitet werden

### ISSUE THREAD

**Issue by ChristinaGu** [wirDesign-communication-AG/wirHub-doc#59]
z.B. hier unter "Informationshierarchie schafft Struktur"
https://brandnet.kws.com/default/style/category/design-simplification

**Comment by pmdevelopment** [comment]
Das Problem ist nicht allgemein sondern speziell für diesen Block, weil der Punkt "4" fehlt. Wie das möglich war ist mir unklar, ich versuche es zu lösen.
