### ISSUE TITLE
SmartBlock Icon-List: Erweiterte Frontend-Optionen

### ISSUE THREAD

**Issue by ChristinaGu** [wirDesign-communication-AG/wirHub-doc#65]
- [x]  "Suche anzeigen" und "Icon-Farben können verändert werden" in den Reiter "Optionen" verschieben
- [x] "Suche anzeigen" bitte mit der Headline "Suche" ergänzen
- [x] "Icon-Farben können verändert werden" bitte mit der Headline "Icon Farbe" ergänzen
- [x] Darunter die neue Option "Größere Darstellung der Icons" mit der Headline "Darstellungsoptionen"
- [x] Kommentare bitte nach ganz unten -> die neue Reihenfolge ist also Suche, Icon Farbe, Darstellungsoptionen, Kommentare

Wird diese Option aktiviert, werden die Icons zum Einen in der Übersicht über die volle Höhe und Breite dargestellt und zum Anderen wird ein größeres Modal dargestellt in der ebenfalls die Ansicht des Icons angepasst wird (siehe Screenshot wie besprochen). 

<img width="1639" alt="Bildschirmfoto 2021-07-02 um 14 53 28-1" src="https://user-images.githubusercontent.com/8007132/124578691-b9be3d80-de4e-11eb-8f0a-ad5e0d5e448c.png">

**KWS-21076 / 2h**

**Comment by pmdevelopment** [comment]
@ChristinaGu du kannst dir v2.3.3 auf KWS Staging deployen um es mal anzuschauen.
