### ISSUE TITLE
SmartBlocks direkt verlinken

### ISSUE THREAD

**Issue by pmdevelopment** [wirDesign-communication-AG/wirHub-doc#67]
Im Text-Modul kann ich einen Link auf eine Headline erstellen. Dabei wird ein Short-Link erstellt, der auch bei Änderung des Pfads weiter gültig ist.

Es wäre praktisch, wenn man so einen Short-Link für jedes Element erstellen kann, bspw. Nadine hätte es bereits konkret benötigt.

Vorschlag: In der Toolbar im "More"-Bereich als Menüpunkt "Direktlink".

**Zugehöriges Redmine Ticket** 
#7266

**Job**
Mehraufwände Programmierung

**Budget** 
4-6h

**Comment by ChristinaGu** [comment]
Hello @pmdevelopment  - das betrifft ja Redmine Ticket #7266. Bitte daher den Aufwand hierfür auf Mehraufwände Programmierung buchen und mit Prio in diesem Sprint umsetzen
