### ISSUE TITLE
SmartBlock Video: Vorschaubild löschen

### ISSUE THREAD

**Issue by ChristinaGu** [wirDesign-communication-AG/wirHub-doc#7]
Aktuell ist es nicht möglich das Vorschaubild zu löschen, siehe #382. Bitte Feature erweitern. Bei hover über das bestehende Bild Overlay mit Mülleimer analog zu bereits bestehenden Löschfunktionen einblenden.

Frage: betrifft das dann automatisch auch alle anderen Smart-Blocks in denen diese Dropzone verwendet wird wie z.B. Bild.
![Bildschirmfoto 2021-03-29 um 20 33 00](https://user-images.githubusercontent.com/8007132/112883050-0f57b100-90ce-11eb-95b5-12d6f6465829.png)

**Comment by karatektus** [comment]
"Frage: betrifft das dann automatisch auch alle anderen Smart-Blocks in denen diese Dropzone verwendet wird wie z.B. Bild."

Die Antwort lautet "Nein, wäre aber bei manchen aktivierbar, bei 'Bild' im speziellen noch mit etwas extraaufwand."
