### ISSUE TITLE
SmartBlock Lottie: Validierung des Uploads

### ISSUE THREAD

**Issue by pmdevelopment** [wirDesign-communication-AG/wirHub-doc#72]
Scherzkekse laden beim Anlegen eines Lottie-Blocks auch mal ein Video statt eines JSON hoch. Beim Speichern sollte der Inhalt validiert werden.

**Comment by karatektus** [comment]
done. ChunkedUploadType hat nun die optionen mimetype ( array|string ) und mimetype_error_message
